{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interloper.fullname" . }}
  labels:
    {{- include "interloper.labels" . | nindent 4 }}
type: Opaque
stringData:
  INTERLOPER_POSTGRES_PASSWORD: {{ required "secrets.postgresPassword is required" .Values.secrets.postgresPassword | quote }}
  {{- if .Values.secrets.encryptionKey }}
  SECRETS_ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  {{- end }}
  {{- if .Values.secrets.smtpPassword }}
  INTERLOPER_SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.googleClientSecret }}
  INTERLOPER_AUTH_GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  {{- end }}
  {{- range $provider, $secret := .Values.secrets.oauthClientSecrets }}
  {{- if $secret }}
  INTERLOPER_OAUTH_{{ $provider | upper }}_CLIENT_SECRET: {{ $secret | quote }}
  {{- end }}
  {{- end }}
{{- end }}
