import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class Ads(Schema):
    """The Bing Ads report provides insights into advertising campaigns. It includes key metrics such as clicks, conversions, impressions, spend, and various ad attributes like titles, descriptions, and URLs."""

    absolute_top_impression_rate_percent: float | None = Field(..., description="The absolute top impression rate percent")
    account_id: str | None = Field(..., description="The ID of the account")
    account_name: str | None = Field(..., description="The name of the account")
    account_number: str | None = Field(..., description="The account number")
    account_status: str | None = Field(..., description="The status of the account")
    ad_description: str | None = Field(..., description="The description of the ad")
    ad_description_2: str | None = Field(..., description="The second description of the ad")
    ad_distribution: str | None = Field(..., description="The distribution of the ad")
    ad_group_id: str | None = Field(..., description="The ID of the ad group")
    ad_group_name: str | None = Field(..., description="The name of the ad group")
    ad_group_status: str | None = Field(..., description="The status of the ad group")
    ad_id: str | None = Field(..., description="The ID of the ad")
    ad_labels: str | None = Field(..., description="The ad labels")
    ad_status: str | None = Field(..., description="The status of the ad")
    ad_title: str | None = Field(..., description="The title of the ad")
    ad_type: str | None = Field(..., description="The type of the ad")
    all_conversion_rate: float | None = Field(..., description="The conversion rate for all conversions")
    all_conversions: int | None = Field(..., description="All conversions")
    all_conversions_qualified: float | None = Field(..., description="The qualified conversions for all conversions")
    all_cost_per_conversion: float | None = Field(..., description="The cost per conversion for all conversions")
    all_return_on_ad_spend: float | None = Field(..., description="The return on ad spend for all conversions")
    all_revenue: float | None = Field(..., description="All revenue")
    all_revenue_per_conversion: float | None = Field(..., description="The revenue per conversion for all conversions")
    assists: int | None = Field(..., description="The number of assists")
    average_cpc: float | None = Field(..., description="The average cost per click")
    average_cpm: float | None = Field(..., description="The average cost per thousand impressions")
    average_position: float | None = Field(..., description="The average position")
    base_campaign_id: str | None = Field(..., description="The ID of the base campaign")
    bid_match_type: str | None = Field(..., description="The bid match type")
    business_name: str | None = Field(..., description="The business name")
    campaign_id: str | None = Field(..., description="The ID of the campaign")
    campaign_name: str | None = Field(..., description="The name of the campaign")
    campaign_status: str | None = Field(..., description="The status of the campaign")
    campaign_type: str | None = Field(..., description="The type of the campaign")
    clicks: int | None = Field(..., description="The number of clicks")
    conversion_rate: float | None = Field(..., description="The conversion rate")
    conversions: int | None = Field(..., description="The number of conversions")
    conversions_qualified: float | None = Field(..., description="The qualified conversions")
    cost_per_assist: float | None = Field(..., description="The cost per assist")
    cost_per_conversion: float | None = Field(..., description="The cost per conversion")
    ctr: float | None = Field(..., description="The click-through rate")
    currency_code: str | None = Field(..., description="The currency code")
    custom_parameters: str | None = Field(..., description="The custom parameters")
    customer_id: str | None = Field(..., description="The ID of the customer")
    customer_name: str | None = Field(..., description="The name of the customer")
    delivered_match_type: str | None = Field(..., description="The delivered match type")
    destination_url: str | None = Field(..., description="The destination URL")
    device_os: str | None = Field(..., description="The device OS")
    device_type: str | None = Field(..., description="The device type")
    display_url: str | None = Field(..., description="The display URL")
    final_app_url: str | None = Field(..., description="The final app URL")
    final_mobile_url: str | None = Field(..., description="The final mobile URL")
    final_url: str | None = Field(..., description="The final URL")
    final_url_suffix: str | None = Field(..., description="The suffix of the final URL")
    goal: str | None = Field(..., description="The goal")
    goal_type: str | None = Field(..., description="The type of the goal")
    headline: str | None = Field(..., description="The headline")
    impressions: int | None = Field(..., description="The number of impressions")
    language: str | None = Field(..., description="The language")
    long_headline: str | None = Field(..., description="The long headline")
    network: str | None = Field(..., description="The network")
    path_1: str | None = Field(..., description="The first path")
    path_2: str | None = Field(..., description="The second path")
    return_on_ad_spend: float | None = Field(..., description="The return on ad spend")
    revenue: float | None = Field(..., description="The revenue")
    revenue_per_assist: float | None = Field(..., description="The revenue per assist")
    revenue_per_conversion: float | None = Field(..., description="The revenue per conversion")
    spend: float | None = Field(..., description="The total spend")
    time_period: dt.date | None = Field(..., description="The time period")
    title_part_1: str | None = Field(..., description="The first part of the title")
    title_part_2: str | None = Field(..., description="The second part of the title")
    title_part_3: str | None = Field(..., description="The third part of the title")
    top_impression_rate_percent: float | None = Field(..., description="The top impression rate percent")
    top_vs_other: str | None = Field(..., description="The top vs other")
    tracking_template: str | None = Field(..., description="The tracking template")
    view_through_conversions: float | None = Field(..., description="The view-through conversions")
    view_through_conversions_qualified: float | None = Field(..., description="The qualified view-through conversions")
    view_through_revenue: float | None = Field(..., description="The view-through revenue")
