site_name: Interloper

repo_name: digitl-cloud/interloper-core
repo_url: https://github.com/digitl-cloud/interloper-core

theme:
  name: material
  features:
    - announce.dismiss
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    scheme: slate
    primary: black
    accent: lime
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/rocket

plugins:
  - blog
  - search
  # - minify:
  #     minify_html: true

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Tutorial: tutorial.md
  - Features:
    - Basic: features/basic.md
    - IO: features/io.md
    - Schema: features/schema.md
    - Upstream assets: features/upstream-assets.md
    - Data Validation: features/data-validation.md
    - Partitioning: features/partitioning.md
    - Backfilling: features/backfilling.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences