# ###############
# UV
# ###############
[project]
name = "deeead"
version = "0.1.0"
description = "Does Everything Already Done"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dead",
    "dead-assets",
    "dead-duckdb",
    "dead-pandas",
    "dead-sql",
    "dead-sqlite",
    "matplotlib>=3.10.0",
    "streamlit>=1.42.2",
]

[tool.uv.sources]
dead = { workspace = true }
dead-assets = { workspace = true }
dead-duckdb = { workspace = true }
dead-pandas = { workspace = true }
dead-sql = { workspace = true }
dead-sqlite = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = ["pyright>=1.1.393", "ruff>=0.9.4"]

# ###############
# PYRIGHT
# ###############
[tool.pyright]
typeCheckingMode = "basic"
reportMissingParameterType = true
