# ###############
# UV
# ###############
[project]
name = "interloper"
version = "0.1.0"
description = "Interloper"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "interloper-core",
    "interloper-assets",
    "interloper-duckdb",
    "interloper-pandas",
    "interloper-sql",
    "interloper-sqlite",
    "matplotlib>=3.10.0",
    "streamlit>=1.42.2",
]

[dependency-groups]
dev = ["mkdocs-material>=9.6.7", "pyright>=1.1.393", "ruff>=0.9.4"]

[tool.uv.sources]
interloper-core = { workspace = true }
interloper-assets = { workspace = true }
interloper-duckdb = { workspace = true }
interloper-pandas = { workspace = true }
interloper-sql = { workspace = true }
interloper-sqlite = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]


# ###############
# PYRIGHT
# ###############
[tool.pyright]
typeCheckingMode = "basic"
reportMissingParameterType = true


# ###############
# RUFF
# ###############
[tool.ruff]
target-version = "py310"
line-length = 120
exclude = ["libs/**"]

[tool.ruff.lint]
extend-select = ["E", "I", "UP", "ANN001", "ANN201", "ANN202"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"tests/**" = ["ANN"]
