# ###############
# UV
# ###############
[project]
name = "interloper"
version = "0.1.0"
description = "Interloper"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "interloper-core",
    "interloper-assets",
    "interloper-duckdb",
    "interloper-pandas",
    "interloper-sql",
    "interloper-sqlite",
    "matplotlib>=3.10.0",
    "streamlit>=1.42.2",
]

[tool.uv.sources]
interloper-core = { workspace = true }
interloper-assets = { workspace = true }
interloper-duckdb = { workspace = true }
interloper-pandas = { workspace = true }
interloper-sql = { workspace = true }
interloper-sqlite = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = ["pyright>=1.1.393", "ruff>=0.9.4"]

# ###############
# PYRIGHT
# ###############
[tool.pyright]
typeCheckingMode = "basic"
reportMissingParameterType = true
