from interloper.schema import Schema
from pydantic import Field


class AdGroups(Schema):
    """Pinterest ad group metadata including targeting, budget, and scheduling details."""

    id: int = Field(description="The unique identifier for the ad group")
    ad_account_id: int = Field(description="The unique identifier for the ad account")
    campaign_id: int = Field(description="The unique identifier for the campaign")
    name: str = Field(description="The name of the ad group")
    status: str = Field(description="The status of the ad group")
    type: str = Field(description="The type of the ad group")
    summary_status: str = Field(description="The summary status of the ad group")
    review_status: str = Field(description="The review status of the ad")
    bid_in_micro_currency: float = Field(description="The bid amount in micro currency units")
    bid_strategy_type: str = Field(description="The type of bid strategy used")
    billable_event: str = Field(description="The event that triggers billing for the ad")
    budget_in_micro_currency: float = Field(description="The budget amount in micro currency units")
    budget_type: str = Field(description="The type of budget allocated for the ad group")
    creative_type: str = Field(description="The type of creative used in the ad")
    pacing_delivery_type: str = Field(description="The type of pacing delivery used")
    placement_group: str = Field(description="The group placement for the ad")
    auto_targeting_enabled: bool = Field(description="Indicates whether auto-targeting is enabled")
    is_creative_optimization: bool = Field(description="Indicates whether creative optimization is enabled")
    is_pin_deleted: bool = Field(description="Indicates whether the pin is deleted")
    is_removable: bool = Field(description="Indicates whether the ad group is removable")
    lifetime_frequency_cap: int = Field(description="The lifetime frequency cap for the ad group")
    pin_id: int = Field(description="The unique identifier for the pin")
    start_time: float = Field(description="The start time for the ad group in epoch format")
    end_time: float = Field(description="The end time for the ad group in epoch format")
    feed_profile_id: str = Field(description="The profile ID for the feed associated with the ad")
    destination_url: str = Field(description="The destination URL for the ad")
    android_deep_link: str = Field(description="The deep link URL for Android devices")
    ios_deep_link: str = Field(description="The deep link URL for iOS devices")
    grid_click_type: str = Field(description="The type of grid click associated with the ad")
    customizable_cta_type: str = Field(description="The type of customizable call-to-action used")
    carousel_destination_urls: str = Field(description="The destination URLs for carousel ads")
    rejected_reasons: str = Field(description="The reasons for rejection of the ad")
    rejection_labels: str = Field(description="Labels associated with the rejection of the ad")
    optimization_goal_metadata_frequency_goal_metadata: str = Field(
        description="The metadata for frequency goal optimization"
    )
    targeting_spec_age_bucket: str = Field(description="The age buckets targeted by the ad")
    targeting_spec_apptype: str = Field(description="The app types targeted by the ad")
    targeting_spec_audience_include: str = Field(description="The audience segments included in the targeting")
    targeting_spec_gender: str = Field(description="The genders targeted by the ad")
    targeting_spec_interest: str = Field(description="The interests targeted by the ad")
    targeting_spec_locale: str = Field(description="The locales targeted by the ad")
    targeting_spec_location: str = Field(description="The locations targeted by the ad")
    targeting_spec_targeting_strategy: str = Field(description="The targeting strategies used for the ad")
    created_time: int = Field(description="The timestamp when the ad group was created")
    updated_time: int = Field(description="The timestamp when the ad group was last updated")
