import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class AdsConversionsStats(Schema):
    """Pinterest Ads detailed conversion report with attribution breakdowns across channels and devices."""

    date: dt.date = Field(description="Date of the data")
    # Identifiers
    ad_account_id: str = Field(description="Unique identifier for the ad account")
    ad_group_id: str = Field(description="Unique identifier for the ad group")
    ad_group_name: str = Field(description="Name of the ad group")
    ad_group_entity_status: str = Field(description="Status of the ad group entity")
    ad_group_status: str = Field(description="Status of the ad group")
    ad_id: str = Field(description="Unique identifier for the ad")
    ad_name: str = Field(description="Name of the ad")
    ad_status: str = Field(description="Status of the ad")
    advertiser_id: str = Field(description="Unique identifier for the advertiser")
    campaign_id: str = Field(description="Unique identifier for the campaign")
    campaign_name: str = Field(description="Name of the campaign")
    campaign_entity_status: str = Field(description="Status of the campaign entity")
    campaign_managed_status: str = Field(description="Managed status of the campaign")
    campaign_status: str = Field(description="Status of the campaign")
    campaign_objective_type: str = Field(description="Objective type of the campaign")
    pin_id: str = Field(description="Unique identifier for the pin")
    pin_promotion_id: str = Field(description="Unique identifier for the pin promotion")
    pin_promotion_name: str = Field(description="Name of the pin promotion")
    pin_promotion_status: str = Field(description="Status of the pin promotion")
    # Budget & bid
    ad_group_bid_multiplier: float = Field(description="Bid multiplier for the ad group")
    ad_group_budget_in_local_currency: float = Field(description="Ad group budget in local currency")
    ad_group_budget_type: str = Field(description="Budget type for the ad group")
    ad_group_optimization: str = Field(description="Optimization setting for the ad group")
    campaign_budget_optimization: str = Field(description="Campaign budget optimization status")
    campaign_daily_spend_cap: float = Field(description="Daily spending cap for the campaign")
    campaign_lifetime_spend_cap: float = Field(description="Lifetime spending cap for the campaign")
    is_premiere_campaign: str = Field(description="Whether the campaign is a premiere campaign")
    # Cost metrics
    cpc_in_micro_dollar: float = Field(description="Cost per click in micro dollars")
    cpcv_in_micro_dollar: float = Field(description="Cost per completed video view in micro dollars")
    cpcv_p95_in_micro_dollar: float = Field(description="Cost per 95% video view in micro dollars")
    cpm_in_dollar: float = Field(description="Cost per thousand impressions in dollars")
    cpm_in_micro_dollar: float = Field(description="Cost per thousand impressions in micro dollars")
    cpv_in_micro_dollar: float = Field(description="Cost per video view in micro dollars")
    ctr: float = Field(description="Click-through rate")
    ctr_2: float = Field(description="Secondary click-through rate")
    ecpc_in_dollar: float = Field(description="Effective cost per click in dollars")
    ecpc_in_micro_dollar: float = Field(description="Effective cost per click in micro dollars")
    ecpcv_in_dollar: float = Field(description="Effective cost per completed view in dollars")
    ecpcv_p95_in_dollar: float = Field(description="Effective cost per 95% view in dollars")
    ecpe_in_dollar: float = Field(description="Effective cost per engagement in dollars")
    ecpm_in_micro_dollar: float = Field(description="Effective cost per thousand impressions in micro dollars")
    ecpv_in_dollar: float = Field(description="Effective cost per view in dollars")
    ectr: float = Field(description="Earned click-through rate")
    eengagement_rate: float = Field(description="Earned engagement rate")
    # Engagement
    engagement_1: int = Field(description="Engagement count (paid)")
    engagement_2: int = Field(description="Engagement count (earned)")
    engagement_rate: float = Field(description="Engagement rate")
    clickthrough_1: int = Field(description="Click-through count (paid)")
    clickthrough_1_gross: int = Field(description="Gross click-through count (paid)")
    clickthrough_2: int = Field(description="Click-through count (earned)")
    impression_1_gross: int = Field(description="Gross impression count (paid)")
    impression_2: int = Field(description="Impression count (earned)")
    outbound_click_1: int = Field(description="Outbound click count (paid)")
    outbound_click_2: int = Field(description="Outbound click count (earned)")
    outbound_ctr_1: float = Field(description="Outbound click-through rate (paid)")
    repin_1: int = Field(description="Repin count (paid)")
    repin_2: int = Field(description="Repin count (earned)")
    repin_rate: float = Field(description="Repin rate")
    paid_impression: int = Field(description="Paid impression count")
    paid_video_viewable_rate: float = Field(description="Viewable rate for paid video")
    # Spend
    spend_in_dollar: float = Field(description="Total spend in dollars")
    spend_in_micro_dollar: float = Field(description="Total spend in micro dollars")
    # Product & order
    order_line_id: str = Field(description="Order line identifier")
    order_line_name: str = Field(description="Order line name")
    product_group_id: str = Field(description="Product group identifier")
    product_group_status: str = Field(description="Product group status")
    product_group_ad_image_tag: str = Field(description="Product group ad image tag")
    product_group_ad_video_tag: str = Field(description="Product group ad video tag")
    product_item_brand: str = Field(description="Product item brand")
    product_item_currency: str = Field(description="Product item currency")
    product_item_description: str = Field(description="Product item description")
    product_item_image_url: str = Field(description="Product item image URL")
    product_item_name: str = Field(description="Product item name")
    product_item_pin_url: str = Field(description="Product item Pin URL")
    product_item_price: float = Field(description="Product item price")
    product_item_product_category: str = Field(description="Product item category")
    product_item_product_type: str = Field(description="Product item type")
    product_item_product_url: str = Field(description="Product item URL")
    product_item_sale_price: float = Field(description="Product item sale price")
    promo_id: str = Field(description="Promo identifier")
    promo_name: str = Field(description="Promo name")
    standard_ad_feed_item_id: str = Field(description="Standard ad feed item identifier")
    # Leads & conversions
    cost_per_lead: float = Field(description="Cost per lead")
    leads: int = Field(description="Total number of leads")
    checkout_roas: float = Field(description="Return on ad spend for checkouts")
    custom_roas: float = Field(description="Return on ad spend for custom events")
    # Cost per action
    cost_per_outbound_click_in_dollar: float = Field(description="Cost per outbound click in dollars")
    cost_per_outbound_click_in_dollar_1: float = Field(description="Cost per outbound click in dollars (paid)")
    app_install_cost_per_action: float = Field(description="Cost per app install action")
    page_visit_cost_per_action: float = Field(description="Cost per page visit action")
    page_visit_roas: float = Field(description="Return on ad spend for page visits")
    pinterest_checkout_cost_per_action: float = Field(description="Cost per Pinterest checkout action")
    pinterest_checkout_roas: float = Field(description="Return on ad spend for Pinterest checkouts")
    onsite_checkouts_1: int = Field(description="Onsite checkout count (paid)")
    # Quiz
    quiz_completed: int = Field(description="Number of quizzes completed")
    quiz_completion_rate: float = Field(description="Quiz completion rate")
    # Showcase
    showcase_average_subpage_closeup_per_session: float = Field(
        description="Average subpage closeups per session for showcase ads"
    )
    showcase_card_thumbnail_swipe_backward: int = Field(description="Showcase card thumbnail swipe backward count")
    showcase_card_thumbnail_swipe_forward: int = Field(description="Showcase card thumbnail swipe forward count")
    showcase_pin_clickthrough: int = Field(description="Showcase pin click-through count")
    showcase_subpage_clickthrough: int = Field(description="Showcase subpage click-through count")
    showcase_subpage_closeup: int = Field(description="Showcase subpage closeup count")
    showcase_subpage_impression: int = Field(description="Showcase subpage impression count")
    showcase_subpage_repin: int = Field(description="Showcase subpage repin count")
    showcase_subpage_swipe_left: int = Field(description="Showcase subpage swipe left count")
    showcase_subpage_swipe_right: int = Field(description="Showcase subpage swipe right count")
    showcase_subpin_clickthrough: int = Field(description="Showcase subpin click-through count")
    showcase_subpin_impression: int = Field(description="Showcase subpin impression count")
    showcase_subpin_repin: int = Field(description="Showcase subpin repin count")
    showcase_subpin_swipe_left: int = Field(description="Showcase subpin swipe left count")
    showcase_subpin_swipe_right: int = Field(description="Showcase subpin swipe right count")
    # Idea pin
    idea_pin_page_backward_1: int = Field(description="Idea pin page backward (paid)")
    idea_pin_page_backward_2: int = Field(description="Idea pin page backward (earned)")
    idea_pin_page_forward_1: int = Field(description="Idea pin page forward (paid)")
    idea_pin_page_forward_2: int = Field(description="Idea pin page forward (earned)")
    idea_pin_product_tag_visit_1: int = Field(description="Idea pin product tag visit (paid)")
    idea_pin_product_tag_visit_2: int = Field(description="Idea pin product tag visit (earned)")
