# ###############
# UV
# ###############
[project]
name = "interloper-core"
version = "0.1.0"
description = "Interloper Core"
authors = [{ name = "Guillaume Onfroy", email = "guillaume@digitlcloud.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["httpx>=0.27.2", "networkx>=3.4.2", "typing-extensions>=4.12.2"]

[dependency-groups]
dev = ["pyright>=1.1.394", "ruff>=0.9.6"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/interloper"]

# ###############
# RUFF
# ###############
[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["E", "I", "UP", "ANN001", "ANN201", "ANN202"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

# ###############
# PYRIGHT
# ###############
[tool.pyright]
include = ["src"]
typeCheckingMode = "basic"
reportMissingParameterType = true
ignore = ["libs/**", "tests/**", "scripts/**"]
