BASE_URL = "https://graph.facebook.com"

API_VERSION = "20.0"

ACCOUNT_FIELDS = [
    "account_id",
    "account_status",
    "activities",
    "age",
    "agency_client_declaration",
    "amount_spent",
    "attribution_spec",
    "balance",
    "can_create_brand_lift_study",
    "created_time",
    "currency",
    "disable_reason",
    "end_advertiser_name",
    "end_advertiser",
    "extended_credit_invoice_group",
    "failed_delivery_checks",
    "fb_entity",
    "funding_source_details",
    "funding_source",
    "has_advertiser_opted_in_odax",
    "has_migrated_permissions",
    "id",
    "insights",
    "io_number",
    "is_attribution_spec_system_default",
    "is_direct_deals_enabled",
    "is_in_3ds_authorization_enabled_market",
    "is_notifications_enabled",
    "is_personal",
    "is_prepay_account",
    "is_tax_id_required",
    "line_numbers",
    "media_agency",
    "min_campaign_group_spend_cap",
    "min_daily_budget",
    "name",
    "offsite_pixels_tos_accepted",
    "partner",
    "spend_cap",
    "tax_id_status",
    "tax_id_type",
    "tax_id",
    "timezone_id",
    "timezone_name",
    "timezone_offset_hours_utc",
    "tos_accepted",
    "user_tasks",
    "user_tos_accepted",
    # "ad_account_promotable_objects",
    # "business_city",
    # "business_country_code",
    # "business_name",
    # "business_state",
    # "business_street",
    # "business_street2",
    # "business_zip",
    # "business",
    # "existing_customers",
    # "has_page_authorized_adaccount",
    # "owner",
    # "rf_spec", # valid but verbose
    # "show_checkout_experience",
    # "capabilities",  # valid but verbose
]

CAMPAIGN_FIELDS = [
    "account_id",
    # "activities",
    # "ad_strategy_group_id",
    # "ad_strategy_id",
    "adlabels",
    "bid_strategy",
    "boosted_object_id",
    "brand_lift_studies",
    "budget_rebalance_flag",
    "budget_remaining",
    "buying_type",
    "can_create_brand_lift_study",
    "can_use_spend_cap",
    "configured_status",
    "created_time",
    "daily_budget",
    "effective_status",
    "id",
    # "insights",
    "is_skadnetwork_attribution",
    "issues_info",
    "last_budget_toggling_time",
    "lifetime_budget",
    "name",
    "objective",
    "pacing_type",
    "promoted_object",
    "recommendations",
    "smart_promotion_type",
    "source_campaign_id",
    "source_campaign",
    "special_ad_categories",
    "special_ad_category_country",
    "special_ad_category",
    "spend_cap",
    "start_time",
    "status",
    "stop_time",
    "topline_id",
    "updated_time",
]

ADS_FIELDS = [
    "account_currency",
    "account_id",
    "account_name",
    "action_values",
    "actions",
    "ad_id",
    "ad_name",
    "adset_id",
    "adset_name",
    "attribution_setting",
    "buying_type",
    "campaign_id",
    "campaign_name",
    "clicks",
    "converted_product_quantity",
    "cost_per_action_type",
    "cost_per_conversion",
    "cost_per_inline_link_click",
    "cost_per_inline_post_engagement",
    "cost_per_outbound_click",
    "cost_per_unique_action_type",
    "cost_per_unique_click",
    "cost_per_unique_inline_link_click",
    "cost_per_unique_outbound_click",
    "cpc",
    "cpm",
    "cpp",
    "ctr",
    "date_start",
    "date_stop",
    "frequency",
    "estimated_ad_recallers",
    "impressions",
    "inline_link_click_ctr",
    "inline_link_clicks",
    "inline_post_engagement",
    "objective",
    "optimization_goal",
    "outbound_clicks_ctr",
    "outbound_clicks",
    "quality_ranking",
    "reach",
    "social_spend",
    "spend",
    "unique_actions",
    "unique_clicks",
    "unique_ctr",
    "unique_inline_link_click_ctr",
    "unique_inline_link_clicks",
    "unique_link_clicks_ctr",
    "unique_outbound_clicks_ctr",
    "unique_outbound_clicks",
    "website_ctr",
]

CAMPAINGS_FIELDS = [
    "account_currency",
    "account_id",
    "account_name",
    "action_values",
    "actions",
    "attribution_setting",
    "buying_type",
    "campaign_id",
    "campaign_name",
    "clicks",
    "conversion_rate_ranking",
    "conversion_values",
    "conversions",
    "converted_product_quantity",
    "cost_per_action_type",
    "cost_per_conversion",
    "cost_per_inline_link_click",
    "cost_per_inline_post_engagement",
    "cost_per_outbound_click",
    "cost_per_unique_action_type",
    "cost_per_unique_click",
    "cost_per_unique_inline_link_click",
    "cost_per_unique_outbound_click",
    "cpc",
    "cpm",
    "cpp",
    "ctr",
    "date_start",
    "date_stop",
    "dda_results",
    "engagement_rate_ranking",
    "estimated_ad_recallers",
    "frequency",
    "full_view_impressions",
    "full_view_reach",
    "impressions",
    "inline_link_click_ctr",
    "inline_link_clicks",
    "inline_post_engagement",
    "instant_experience_clicks_to_open",
    "instant_experience_clicks_to_start",
    "instant_experience_outbound_clicks",
    "objective",
    "optimization_goal",
    "outbound_clicks_ctr",
    "outbound_clicks",
    "qualifying_question_qualify_answer_rate",
    "quality_ranking",
    "reach",
    "social_spend",
    "spend",
    "unique_actions",
    "unique_clicks",
    "unique_ctr",
    "unique_inline_link_click_ctr",
    "unique_inline_link_clicks",
    "unique_link_clicks_ctr",
    "unique_outbound_clicks_ctr",
    "unique_outbound_clicks",
    "website_ctr",
]

GEO_FIELDS = [
    "account_currency",
    "account_id",
    "account_name",
    "action_values",
    "ad_id",
    "ad_name",
    "adset_id",
    "adset_name",
    "campaign_id",
    "campaign_name",
    "clicks",
    "conversions",
    "cost_per_conversion",
    "cpc",
    "cpm",
    "cpp",
    "ctr",
    "date_start",
    "date_stop",
    "impressions",
    "reach",
    "social_spend",
    "spend",
]

GENDER_AGE_FIELDS = [
    "account_currency",
    "account_id",
    "account_name",
    "action_values",
    "ad_id",
    "ad_name",
    "adset_id",
    "adset_name",
    "campaign_id",
    "campaign_name",
    "clicks",
    "conversions",
    "cost_per_conversion",
    "cpc",
    "cpm",
    "cpp",
    "ctr",
    "date_start",
    "date_stop",
    "impressions",
    "reach",
    "social_spend",
    "spend",
]

VIDEOS_FIELDS = [
    "account_currency",
    "account_id",
    "account_name",
    "action_values",
    "actions",
    "ad_id",
    "ad_name",
    "adset_id",
    "adset_name",
    "attribution_setting",
    "buying_type",
    "campaign_id",
    "campaign_name",
    "video_30_sec_watched_actions",
    "video_avg_time_watched_actions",
    "video_p100_watched_actions",
    "video_p25_watched_actions",
    "video_p50_watched_actions",
    "video_p75_watched_actions",
    "video_p95_watched_actions",
    "video_play_actions",
    "video_play_curve_actions",
    "website_ctr",
]

AD_FIELDS = [
    "id",
    "account_id",
    "ad_active_time",
    "ad_review_feedback",
    "ad_schedule_end_time",
    "ad_schedule_start_time",
    "adlabels",
    "adset",
    "adset_id",
    "bid_amount",
    "campaign",
    "campaign_id",
    "configured_status",
    "conversion_domain",
    "created_time",
    "creative",
    "effective_status",
    "issues_info",
    "last_updated_by_app_id",
    "name",
    "source_ad",
    "source_ad_id",
    "status",
    "tracking_specs",
    "updated_time",
    "view_tags",
]

AD_REACH_FIELDS = [
    "account_id",
    "account_name",
    "campaign_id",
    "campaign_name",
    "date_start",
    "date_stop",
    "reach",
]

CUSTOM_AUDIENCES_FIELDS = [
    "id",
    "name",
    "description",
    "account_id",
    "approximate_count_lower_bound",
    "approximate_count_upper_bound",
]
