from interloper.schema import Schema
from pydantic import Field


class PageStats(Schema):
    """Facebook Page Insights with engagement, impressions, video views, and reaction metrics."""

    page_actions_post_reactions_anger_total: int = Field(description="Daily total post anger reactions of a page")
    page_actions_post_reactions_haha_total: int = Field(description="Daily total post haha reactions of a page")
    page_actions_post_reactions_like_total: int = Field(description="Daily total post like reactions of a page")
    page_actions_post_reactions_love_total: int = Field(description="Daily total post love reactions of a page")
    page_actions_post_reactions_sorry_total: int = Field(description="Daily total post sorry reactions of a page")
    page_actions_post_reactions_wow_total: int = Field(description="Daily total post wow reactions of a page")
    page_actions_post_reactions_total: str = Field(description="Daily total post reactions of a page")
    page_follows: int = Field(description="The number of followers of the Facebook Page")
    page_media_view: int = Field(description="Number of times any content from the page was displayed")
    page_post_engagements: int = Field(description="Number of times people engaged with posts through likes, comments and shares")
    page_posts_impressions_nonviral_unique: int = Field(description="Number of people who had posts enter their screen without social info (unique)")
    page_posts_impressions_nonviral: int = Field(description="Number of times posts entered a screen without social info (total)")
    page_posts_impressions_paid_unique: int = Field(description="Number of people who had posts enter their screen through paid distribution (unique)")
    page_posts_impressions_paid: int = Field(description="Number of times posts entered a screen through paid distribution (total)")
    page_posts_impressions_unique: int = Field(description="Number of people who had posts enter their screen (unique)")
    page_posts_impressions_viral_unique: int = Field(description="Number of people who had posts enter their screen with social info (unique)")
    page_posts_impressions_viral: int = Field(description="Number of times posts entered a screen with social info (total)")
    page_posts_impressions: int = Field(description="Number of times posts entered a screen (total)")
    page_posts_served_impressions_organic_unique: int = Field(description="Number of people served organic posts in News Feed (unique)")
    page_total_actions: int = Field(description="Number of clicks on contact info and call-to-action button")
    page_video_complete_views_30s_autoplayed: int = Field(description="Number of times auto-played videos were viewed for 30 seconds or to the end")
    page_video_complete_views_30s_click_to_play: int = Field(description="Number of times a video was viewed for at least 30s after clicking play")
    page_video_complete_views_30s_organic: int = Field(description="Number of times a video was viewed for at least 30s by organic reach")
    page_video_complete_views_30s_paid: int = Field(description="Number of times a video was viewed for 30s or to end after paid promotion")
    page_video_complete_views_30s_repeat_views: int = Field(description="Number of times a video was viewed for at least 30s outside the first play")
    page_video_complete_views_30s_unique: int = Field(description="Videos played for unique people for at least 30 seconds (unique)")
    page_video_complete_views_30s: int = Field(description="Total times videos were viewed for at least 30 seconds")
    page_video_repeat_views: int = Field(description="Number of times the video was seen outside the first play")
    page_video_view_time: int = Field(description="Total time in milliseconds people spent watching videos")
    page_video_views_autoplayed: int = Field(description="Number of times an auto-played video was viewed for more than 3 seconds")
    page_video_views_by_paid_non_paid: str = Field(description="Total video views broken down by total, paid and non-paid")
    page_video_views_click_to_play: int = Field(description="Number of times a video was viewed after clicking play")
    page_video_views_organic: int = Field(description="Number of times a video was viewed due to organic reach")
    page_video_views_paid: int = Field(description="Number of times a promoted video was viewed for more than 3 seconds")
    page_video_views_unique: int = Field(description="Videos played for unique people for more than 3 seconds (unique)")
    page_video_views: int = Field(description="Total times videos were viewed for more than 3 seconds")
    page_views_total: int = Field(description="Total views count per page")
