from interloper.schema import Schema
from pydantic import Field


class PostStats(Schema):
    """Facebook Post Insights with per-post engagement, clicks, reactions, and video metrics."""

    post_id: str = Field(description="The unique identifier of the post")
    post_activity_by_action_type_unique: str = Field(description="Post activity by action type (unique)")
    post_activity_by_action_type: str = Field(description="Post activity by action type")
    post_clicks_by_type: str = Field(description="Post clicks by type")
    post_clicks: int = Field(description="Total number of post clicks")
    post_media_view: int = Field(description="Number of times post media was viewed")
    post_reactions_anger_total: int = Field(description="Total anger reactions on the post")
    post_reactions_by_type_total: str = Field(description="Total reactions by type on the post")
    post_reactions_haha_total: int = Field(description="Total haha reactions on the post")
    post_reactions_like_total: int = Field(description="Total like reactions on the post")
    post_reactions_love_total: int = Field(description="Total love reactions on the post")
    post_reactions_sorry_total: int = Field(description="Total sorry reactions on the post")
    post_reactions_wow_total: int = Field(description="Total wow reactions on the post")
    post_video_ad_break_ad_cpm: float = Field(description="Ad break CPM for the post video")
    post_video_ad_break_ad_impressions: int = Field(description="Ad break impressions for the post video")
    post_video_ad_break_earnings: float = Field(description="Ad break earnings for the post video")
    post_video_avg_time_watched: int = Field(description="Average time watched for the post video")
    post_video_complete_views_30s_autoplayed: int = Field(description="Number of times auto-played video was viewed for 30 seconds")
    post_video_complete_views_30s_clicked_to_play: int = Field(description="Number of times video was viewed for 30s after clicking play")
    post_video_complete_views_30s_organic: int = Field(description="Number of times video was viewed for 30s by organic reach")
    post_video_complete_views_30s_paid: int = Field(description="Number of times video was viewed for 30s after paid promotion")
    post_video_complete_views_30s_unique: int = Field(description="Unique viewers who watched video for at least 30 seconds")
    post_video_complete_views_organic_unique: int = Field(description="Unique organic viewers who watched entire video")
    post_video_complete_views_organic: int = Field(description="Total organic complete video views")
    post_video_complete_views_paid_unique: int = Field(description="Unique paid viewers who watched entire video")
    post_video_complete_views_paid: int = Field(description="Total paid complete video views")
    post_video_length: float = Field(description="Length of the post video")
    post_video_retention_graph_autoplayed: str = Field(description="Video retention graph for auto-played views")
    post_video_retention_graph_clicked_to_play: str = Field(description="Video retention graph for click-to-play views")
    post_video_retention_graph: str = Field(description="Video retention graph")
    post_video_view_time_by_age_bucket_and_gender: str = Field(description="Video view time by age bucket and gender")
    post_video_view_time_by_country_id: str = Field(description="Video view time by country")
    post_video_view_time_by_distribution_type: str = Field(description="Video view time by distribution type")
    post_video_view_time_by_region_id: str = Field(description="Video view time by region")
    post_video_view_time_organic: int = Field(description="Total organic video view time")
    post_video_view_time: int = Field(description="Total video view time")
    post_video_views_autoplayed: int = Field(description="Number of auto-played video views for more than 3 seconds")
    post_video_views_by_distribution_type: str = Field(description="Video views by distribution type")
    post_video_views_clicked_to_play: int = Field(description="Number of click-to-play video views")
    post_video_views_organic_unique: int = Field(description="Unique organic video views")
    post_video_views_organic: int = Field(description="Total organic video views")
    post_video_views_paid_unique: int = Field(description="Unique paid video views")
    post_video_views_paid: int = Field(description="Total paid video views")
    post_video_views_sound_on: int = Field(description="Number of video views with sound on")
    post_video_views_unique: int = Field(description="Unique video views")
    post_video_views: int = Field(description="Total video views")
