global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["otel-collector:9876"]
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
