import datetime as dt
from dataclasses import field

import interloper as itlp


class Ads(itlp.AssetSchema):
    """
    The Criteo Ads report provides insights into the performance of marketing campaigns aimed at driving online sales and conversions. 
    It includes key metrics such as click-through rate, cost per acquisition, revenue generated, and dimensions such as ad ID, advertiser, and date.
    """

    ad: str = field(metadata={"description": "The name of the ad"})
    ad_id: int = field(metadata={"description": "The unique identifier of the ad"})
    adset: str = field(metadata={"description": "The name of the adset"})
    adset_id: int = field(metadata={"description": "The unique identifier of the adset"})
    advertiser_all_value: float = field(metadata={"description": "The total value generated for the advertiser across all channels and attribution models"})
    advertiser_cost: float = field(metadata={"description": "The total cost incurred by the advertiser for running the advertisement"})
    advertiser_value: float = field(metadata={"description": "The total value generated specifically for the advertiser"})
    app_installs: int = field(metadata={"description": "The number of installations of a particular application attributed to the advertisement"})
    audience: int = field(metadata={"description": "The total audience reached by the advertisement"})
    average_cart_all_client_attribution: float = field(metadata={"description": "The average cart value attributed to the advertisement across all clients"})
    average_cart_all_pc_1d: float = field(metadata={"description": "The average cart value per client attributed to the advertisement within a one-day period"})
    average_cart_all_pc_30d: float = field(metadata={"description": "The average cart value per client attributed to the advertisement within a 30-day period"})
    average_cart_all_pc_30d_pv_24h: float = field(metadata={"description": "The average cart value per client attributed to the advertisement within a 30-day period, considering post-view conversions within 24 hours"})
    average_cart_all_pc_7d: float = field(metadata={"description": "The average cart value per client attributed to the advertisement within a seven-day period"})
    average_cart_all_pv_24h: float = field(metadata={"description": "The average cart value attributed to the advertisement within 24 hours after a post-view conversion"})
    average_cart_client_attribution: float = field(metadata={"description": "The average cart value attributed to the advertisement for each client"})
    average_cart_pc_1d: float = field(metadata={"description": "The average cart value per client attributed to the advertisement within a one-day period"})
    average_cart_pc_30d: float = field(metadata={"description": "The average cart value per client attributed to the advertisement within a 30-day period"})
    average_cart_pc_30d_pv_24h: float = field(metadata={"description": "The average cart value per client attributed to the advertisement within a 30-day period, considering post-view conversions within 24 hours"})
    average_cart_pc_7d: float = field(metadata={"description": "The average cart value per client attributed to the advertisement within a seven-day period"})
    average_cart_pv_24h: float = field(metadata={"description": "The average cart value attributed to the advertisement within 24 hours after a post-view conversion"})
    bounce_rate: float = field(metadata={"description": "The rate at which visitors leave the website after viewing only one page"})
    campaign: str = field(metadata={"description": "The name of the campaign"})
    campaign_id: int = field(metadata={"description": "The unique identifier of the campaign"})
    click_through_rate: float = field(metadata={"description": "The ratio of users who click on a specific link to the number of total users who view a page, email, or advertisement"})
    clicks: int = field(metadata={"description": "The number of times users clicked on the advertisement"})
    conversion_rate_all_client_attribution: float = field(metadata={"description": "The rate at which users who viewed or clicked on the advertisement performed a desired action across all clients"})
    conversion_rate_all_pc_1d: float = field(metadata={"description": "The conversion rate within a one-day period attributed to the advertisement across all clients"})
    conversion_rate_all_pc_30d: float = field(metadata={"description": "The conversion rate within a 30-day period attributed to the advertisement across all clients"})
    conversion_rate_all_pc_30d_pv_24h: float = field(metadata={"description": "The conversion rate within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement across all clients"})
    conversion_rate_all_pc_7d: float = field(metadata={"description": "The conversion rate within a seven-day period attributed to the advertisement across all clients"})
    conversion_rate_all_pv_24h: float = field(metadata={"description": "The conversion rate within 24 hours after a post-view conversion attributed to the advertisement across all clients"})
    conversion_rate_client_attribution: float = field(metadata={"description": "The conversion rate attributed to the advertisement for each client"})
    conversion_rate_pc_1d: float = field(metadata={"description": "The conversion rate within a one-day period attributed to the advertisement for each client"})
    conversion_rate_pc_30d: float = field(metadata={"description": "The conversion rate within a 30-day period attributed to the advertisement for each client"})
    conversion_rate_pc_30d_pv_24h: float = field(metadata={"description": "The conversion rate within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement for each client"})
    conversion_rate_pc_7d: float = field(metadata={"description": "The conversion rate within a seven-day period attributed to the advertisement for each client"})
    conversion_rate_pv_24h: float = field(metadata={"description": "The conversion rate within 24 hours after a post-view conversion attributed to the advertisement for each client"})
    cost_of_advertiser_value: float = field(metadata={"description": "The cost incurred by the advertiser for generating a certain value through the advertisement"})
    cost_of_advertiser_value_all: float = field(metadata={"description": "The total cost incurred by the advertiser for generating value across all channels and attribution models"})
    cost_per_install: int = field(metadata={"description": "The cost incurred by the advertiser for each installation of a particular application attributed to the advertisement"})
    cost_per_order_all_client_attribution: float = field(metadata={"description": "The cost per order attributed to the advertisement across all clients"})
    cost_per_order_all_pc_1d: float = field(metadata={"description": "The cost per order within a one-day period attributed to the advertisement across all clients"})
    cost_per_order_all_pc_30d: float = field(metadata={"description": "The cost per order within a 30-day period attributed to the advertisement across all clients"})
    cost_per_order_all_pc_30d_pv_24h: float = field(metadata={"description": "The cost per order within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement across all clients"})
    cost_per_order_all_pc_7d: float = field(metadata={"description": "The cost per order within a seven-day period attributed to the advertisement across all clients"})
    cost_per_order_all_pv_24h: float = field(metadata={"description": "The cost per order within 24 hours after a post-view conversion attributed to the advertisement across all clients"})
    cost_per_order_client_attribution: float = field(metadata={"description": "The cost per order attributed to the advertisement for each client"})
    cost_per_order_pc_1d: float = field(metadata={"description": "The cost per order within a one-day period attributed to the advertisement for each client"})
    cost_per_order_pc_30d: float = field(metadata={"description": "The cost per order within a 30-day period attributed to the advertisement for each client"})
    cost_per_order_pc_30d_pv_24h: float = field(metadata={"description": "The cost per order within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement for each client"})
    cost_per_order_pc_7d: float = field(metadata={"description": "The cost per order within a seven-day period attributed to the advertisement for each client"})
    cost_per_order_pv_24h: float = field(metadata={"description": "The cost per order within 24 hours after a post-view conversion attributed to the advertisement for each client"})
    cost_per_visit: float = field(metadata={"description": "The cost incurred by the advertiser for each visit to a website attributed to the advertisement"})
    cpc: float = field(metadata={"description": "The cost incurred by the advertiser for each click on the advertisement"})
    currency: str = field(metadata={"description": "The currency used for the cost and revenue values associated with the advertisement"})
    day: dt.date = field(metadata={"description": "The date when the advertisement data was recorded"})
    displays: int = field(metadata={"description": "The total number of times the advertisement was displayed"})
    e_cos_all_client_attribution: float = field(metadata={"description": "The estimated cost of sale attributed to the advertisement across all clients"})
    e_cos_all_pc_1d: float = field(metadata={"description": "The estimated cost of sale within a one-day period attributed to the advertisement across all clients"})
    e_cos_all_pc_30d: float = field(metadata={"description": "The estimated cost of sale within a 30-day period attributed to the advertisement across all clients"})
    e_cos_all_pc_30d_pv_24h: float = field(metadata={"description": "The estimated cost of sale within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement across all clients"})
    e_cos_all_pc_7d: float = field(metadata={"description": "The estimated cost of sale within a seven-day period attributed to the advertisement across all clients"})
    e_cos_all_pv_24h: float = field(metadata={"description": "The estimated cost of sale within 24 hours after a post-view conversion attributed to the advertisement across all clients"})
    e_cos_client_attribution: float = field(metadata={"description": "The estimated cost of sale attributed to the advertisement for each client"})
    e_cos_pc_1d: float = field(metadata={"description": "The estimated cost of sale within a one-day period attributed to the advertisement for each client"})
    e_cos_pc_30d: float = field(metadata={"description": "The estimated cost of sale within a 30-day period attributed to the advertisement for each client"})
    e_cos_pc_30d_pv_24h: float = field(metadata={"description": "The estimated cost of sale within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement for each client"})
    e_cos_pc_7d: float = field(metadata={"description": "The estimated cost of sale within a seven-day period attributed to the advertisement for each client"})
    e_cos_pv_24h: float = field(metadata={"description": "The estimated cost of sale within 24 hours after a post-view conversion attributed to the advertisement for each client"})
    e_cpm: float = field(metadata={"description": "The effective cost per mille (thousand) impressions for the advertisement"})
    exposed_users: int = field(metadata={"description": "The total number of users exposed to the advertisement"})
    install_rate: float = field(metadata={"description": "The rate of installation of a particular application attributed to the advertisement"})
    non_viewable_displays: int = field(metadata={"description": "The total number of times the advertisement was displayed but not viewed by users"})
    omni_channel_revenue_pc_30d: float = field(metadata={"description": "The revenue generated across all channels within a 30-day period attributed to the advertisement"})
    omni_channel_roas_pc_30d: float = field(metadata={"description": "The return on advertising spend across all channels within a 30-day period attributed to the advertisement"})
    omni_channel_sales_pc_30d: int = field(metadata={"description": "The total sales across all channels within a 30-day period attributed to the advertisement"})
    omnichannel_revenue_all_pc_30d: float = field(metadata={"description": "The total revenue generated within a 30-day period across all channels and attribution models attributed to the advertisement"})
    omnichannel_revenue_all_pv_24h: float = field(metadata={"description": "The total revenue generated within 24 hours after a post-view conversion across all channels and attribution models attributed to the advertisement"})
    omnichannel_revenue_client_attribution: float = field(metadata={"description": "The revenue generated attributed to the advertisement for each client across all channels"})
    omnichannel_revenue_pv_24h: float = field(metadata={"description": "The revenue generated within 24 hours after a post-view conversion attributed to the advertisement for each client across all channels"})
    omnichannel_roas_all_pc_30d: float = field(metadata={"description": "The return on advertising spend within a 30-day period across all channels and attribution models attributed to the advertisement"})
    omnichannel_roas_all_pv_24h: float = field(metadata={"description": "The return on advertising spend within 24 hours after a post-view conversion across all channels and attribution models attributed to the advertisement"})
    omnichannel_roas_client_attribution: float = field(metadata={"description": "The return on advertising spend attributed to the advertisement for each client across all channels"})
    omnichannel_roas_pv_24h: float = field(metadata={"description": "The return on advertising spend within 24 hours after a post-view conversion attributed to the advertisement for each client across all channels"})
    omnichannel_sales_all_pc_30d: int = field(metadata={"description": "The total sales within a 30-day period across all channels and attribution models attributed to the advertisement"})
    omnichannel_sales_all_pv_24h: int = field(metadata={"description": "The total sales within 24 hours after a post-view conversion across all channels and attribution models attributed to the advertisement"})
    omnichannel_sales_client_attribution: int = field(metadata={"description": "The sales attributed to the advertisement for each client across all channels"})
    omnichannel_sales_pv_24h: int = field(metadata={"description": "The sales within 24 hours after a post-view conversion attributed to the advertisement for each client across all channels"})
    overall_competition_win: float = field(metadata={"description": "The overall competition win rate attributed to the advertisement"})
    post_install_conversion_rate: float = field(metadata={"description": "The conversion rate after installation attributed to the advertisement"})
    post_install_cost_of_sale: float = field(metadata={"description": "The cost of sale after installation attributed to the advertisement"})
    post_install_cost_per_order: float = field(metadata={"description": "The cost per order after installation attributed to the advertisement"})
    post_install_order_value: float = field(metadata={"description": "The value of orders after installation attributed to the advertisement"})
    post_install_roas: float = field(metadata={"description": "The return on advertising spend after installation attributed to the advertisement"})
    post_install_sales: float = field(metadata={"description": "The sales after installation attributed to the advertisement"})
    potential_displays: int = field(metadata={"description": "The potential number of times the advertisement could have been displayed"})
    qualified_visits: int = field(metadata={"description": "The number of visits that meet certain qualifications attributed to the advertisement"})
    reach: float = field(metadata={"description": "The estimated number of unique users reached by the advertisement"})
    revenue_generated_all_client_attribution: float = field(metadata={"description": "The total revenue generated attributed to the advertisement across all clients"})
    revenue_generated_all_pc_1d: float = field(metadata={"description": "The total revenue generated within a one-day period attributed to the advertisement across all clients"})
    revenue_generated_all_pc_30d: float = field(metadata={"description": "The total revenue generated within a 30-day period attributed to the advertisement across all clients"})
    revenue_generated_all_pc_30d_pv_24h: float = field(metadata={"description": "The total revenue generated within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement across all clients"})
    revenue_generated_all_pc_7d: float = field(metadata={"description": "The total revenue generated within a seven-day period attributed to the advertisement across all clients"})
    revenue_generated_all_pv_24h: float = field(metadata={"description": "The total revenue generated within 24 hours after a post-view conversion attributed to the advertisement across all clients"})
    revenue_generated_client_attribution: float = field(metadata={"description": "The revenue generated attributed to the advertisement for each client"})
    revenue_generated_offline_pc_30d: float = field(metadata={"description": "The revenue generated offline within a 30-day period attributed to the advertisement"})
    revenue_generated_offline_pv_24h: float = field(metadata={"description": "The revenue generated offline within 24 hours after a post-view conversion attributed to the advertisement"})
    revenue_generated_pc_1d: float = field(metadata={"description": "The revenue generated within a one-day period attributed to the advertisement"})
    revenue_generated_pc_30d: float = field(metadata={"description": "The revenue generated within a 30-day period attributed to the advertisement"})
    revenue_generated_pc_30d_pv_24h: float = field(metadata={"description": "The revenue generated within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement"})
    revenue_generated_pc_7d: float = field(metadata={"description": "The revenue generated within a seven-day period attributed to the advertisement"})
    revenue_generated_pv_24h: float = field(metadata={"description": "The revenue generated within 24 hours after a post-view conversion attributed to the advertisement"})
    roas_all_client_attribution: float = field(metadata={"description": "The return on advertising spend attributed to the advertisement for each client across all channels"})
    roas_all_pc_1d: float = field(metadata={"description": "The return on advertising spend within a one-day period attributed to the advertisement across all channels"})
    roas_all_pc_30d: float = field(metadata={"description": "The return on advertising spend within a 30-day period attributed to the advertisement across all channels"})
    roas_all_pc_30d_pv_24h: float = field(metadata={"description": "The return on advertising spend within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement across all channels"})
    roas_all_pc_7d: float = field(metadata={"description": "The return on advertising spend within a seven-day period attributed to the advertisement across all channels"})
    roas_all_pv_24h: float = field(metadata={"description": "The return on advertising spend within 24 hours after a post-view conversion attributed to the advertisement across all channels"})
    roas_client_attribution: float = field(metadata={"description": "The return on advertising spend attributed to the advertisement for each client"})
    roas_offline_pc_30d: float = field(metadata={"description": "The return on advertising spend offline within a 30-day period attributed to the advertisement"})
    roas_offline_pv_24h: float = field(metadata={"description": "The return on advertising spend offline within 24 hours after a post-view conversion attributed to the advertisement"})
    roas_pc_1d: float = field(metadata={"description": "The return on advertising spend within a one-day period attributed to the advertisement"})
    roas_pc_30d: float = field(metadata={"description": "The return on advertising spend within a 30-day period attributed to the advertisement"})
    roas_pc_30d_pv_24h: float = field(metadata={"description": "The return on advertising spend within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement"})
    roas_pc_7d: float = field(metadata={"description": "The return on advertising spend within a seven-day period attributed to the advertisement"})
    roas_pv_24h: float = field(metadata={"description": "The return on advertising spend within 24 hours after a post-view conversion attributed to the advertisement"})
    sales_all_client_attribution: int = field(metadata={"description": "The total sales attributed to the advertisement for each client across all channels"})
    sales_all_pc_1d: int = field(metadata={"description": "The total sales within a one-day period attributed to the advertisement across all channels"})
    sales_all_pc_30d: int = field(metadata={"description": "The total sales within a 30-day period attributed to the advertisement across all channels"})
    sales_all_pc_30d_pv_24h: int = field(metadata={"description": "The total sales within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement across all channels"})
    sales_all_pc_7d: int = field(metadata={"description": "The total sales within a seven-day period attributed to the advertisement across all channels"})
    sales_all_pv_24h: int = field(metadata={"description": "The total sales within 24 hours after a post-view conversion attributed to the advertisement across all channels"})
    sales_client_attribution: int = field(metadata={"description": "The sales attributed to the advertisement for each client across all channels"})
    sales_offline_pc_30d: int = field(metadata={"description": "The offline sales within a 30-day period attributed to the advertisement"})
    sales_offline_pv_24h: int = field(metadata={"description": "The offline sales within 24 hours after a post-view conversion attributed to the advertisement"})
    sales_pc_1d: int = field(metadata={"description": "The total sales within a one-day period attributed to the advertisement"})
    sales_pc_30d: int = field(metadata={"description": "The total sales within a 30-day period attributed to the advertisement"})
    sales_pc_30d_pv_24h: int = field(metadata={"description": "The total sales within a 30-day period, considering post-view conversions within 24 hours, attributed to the advertisement"})
    sales_pc_7d: int = field(metadata={"description": "The total sales within a seven-day period attributed to the advertisement"})
    sales_pv_24h: int = field(metadata={"description": "The total sales within 24 hours after a post-view conversion attributed to the advertisement"})
    untrackable_displays: int = field(metadata={"description": "The number of displays that could not be tracked for the advertisement"})
    viewable_displays: int = field(metadata={"description": "The number of displays that were viewable for the advertisement"})
    visits: int = field(metadata={"description": "The number of visits attributed to the advertisement"})
