API_SERVICE = "searchconsole"
API_VERSION = "v1"
SCOPES = ["https://www.googleapis.com/auth/webmasters.readonly"]

# Search Analytics caps a single response at 25,000 rows; page with startRow.
ROW_LIMIT = 25_000

PAGE_DIMENSIONS = ["DATE", "PAGE", "QUERY", "COUNTRY", "DEVICE"]
SITE_DIMENSIONS = ["DATE", "QUERY", "COUNTRY", "DEVICE"]
SITE_BY_COUNTRY_DEVICE_DIMENSIONS = ["DATE", "COUNTRY", "DEVICE"]
SITE_BY_COUNTRY_PAGE_DIMENSIONS = ["DATE", "COUNTRY", "PAGE"]
SEARCH_APPEARANCE_DIMENSIONS = ["SEARCH_APPEARANCE"]

SEARCH_TYPES = ["WEB", "IMAGE", "VIDEO", "NEWS"]
ALL_SEARCH_TYPES = [*SEARCH_TYPES, "DISCOVER", "GOOGLE_NEWS"]
