# ###############
# PROJECT / UV
# ###############
[project]
name = "interloper"
version = "0.1.0"
description = "Interloper"
authors = [{ name = "Guillaume Onfroy", email = "guillaume@digitlcloud.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["httpx>=0.28.1", "networkx>=3.4.2"]

[project.optional-dependencies]
cli = ["jsonschema>=4.23.0", "pyyaml>=6.0.0", "rich>=14.0.0"]

[dependency-groups]
dev = ["pyright>=1.1.394", "pytest>=8.3.5", "ruff>=0.9.6"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
interloper = "interloper.cli:main"

# ###############
# RUFF
# ###############
[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["E", "I", "UP", "ANN001", "ANN201", "ANN202"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"tests/**" = ["ANN"]

# ###############
# PYRIGHT
# ###############
[tool.pyright]
include = ["src"]
typeCheckingMode = "basic"
reportMissingParameterType = true
ignore = ["libs/**", "tests/**", "scripts/**"]

# ###############
# PYTEST
# ###############
[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
