import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class ActionUpdates(Schema):
    """Action updates report providing detailed information on actions and their associated attributes"""

    action_date: dt.datetime | None = Field(default=None, description="Date when the action occurred")
    action_id: str | None = Field(default=None, description="Unique identifier for the specific action")
    action_tracker_id: str | None = Field(default=None, description="Unique identifier for the action tracker")
    action_uri: str | None = Field(default=None, description="URI associated with the action")
    ad_id: str | None = Field(default=None, description="Unique identifier for the advertisement")
    caller_id: str | None = Field(default=None, description="Identifier for the caller")
    campaign_id: str | None = Field(default=None, description="Unique identifier for the campaign")
    catalog_category: str | None = Field(default=None, description="Category within the catalog")
    catalog_description: str | None = Field(default=None, description="Description of the catalog item")
    catalog_manufacturer: str | None = Field(default=None, description="Manufacturer of the catalog item")
    catalog_name: str | None = Field(default=None, description="Name of the catalog")
    catalog_original_format_category: str | None = Field(default=None, description="Original format category of the catalog item")
    catalog_sub_category: str | None = Field(default=None, description="Sub-category within the catalog")
    category: str | None = Field(default=None, description="Category of the action")
    clearing_date: dt.datetime | None = Field(default=None, description="Date when the action was cleared")
    contract_id: str | None = Field(default=None, description="Identifier for the contract")
    currency: str | None = Field(default=None, description="Currency used for the transaction")
    customer_id: str | None = Field(default=None, description="Unique identifier for the customer")
    customer_status: str | None = Field(default=None, description="Status of the customer")
    default_payout_rate: float | None = Field(default=None, description="Default payout rate for the action")
    delta_amount: float | None = Field(default=None, description="Difference in action amounts")
    delta_payout: float | None = Field(default=None, description="Difference in payout amounts")
    disposition: str | None = Field(default=None, description="Final disposition or status of the action")
    event_code: str | None = Field(default=None, description="Code representing the event type")
    event_type_id: str | None = Field(default=None, description="Identifier for the event type")
    event_type_name: str | None = Field(default=None, description="Name of the event type")
    id: str | None = Field(default=None, description="Unique identifier for the action record")
    locking_date: dt.datetime | None = Field(default=None, description="Date when the action was locked")
    media_partner_id: str | None = Field(default=None, description="Unique identifier for the media partner")
    oid: str | None = Field(default=None, description="Order identifier associated with the action")
    payout_group_id: str | None = Field(default=None, description="Identifier for the payout group")
    payout_group_payout_rate: float | None = Field(default=None, description="Payout rate for the payout group")
    payout_group_rank: str | None = Field(default=None, description="Rank of the payout group")
    payout_group_rules: str | None = Field(default=None, description="Rules for the payout group")
    payout_level: str | None = Field(default=None, description="Level of payout for the action")
    quantity: int | None = Field(default=None, description="Quantity involved in the action")
    shared_id: str | None = Field(default=None, description="Shared identifier for tracking purposes")
    sku: str | None = Field(default=None, description="Stock Keeping Unit associated with the action")
    state: str | None = Field(default=None, description="State of the action (e.g., pending, approved)")
    state_detail: str | None = Field(default=None, description="Detailed description of the action state")
    state_detail_description: str | None = Field(default=None, description="Additional details about the action state")
    sub_category: str | None = Field(default=None, description="Sub-category of the action")
    text_1: str | None = Field(default=None, description="Custom text field 1")
    text_2: str | None = Field(default=None, description="Custom text field 2")
    text_3: str | None = Field(default=None, description="Custom text field 3")
    update_date: dt.datetime | None = Field(default=None, description="Date when the action was last updated")
    uri: str | None = Field(default=None, description="General URI related to the action")
    date: dt.date | None = Field(default=None, description="Partition date")
