import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class PageStats(Schema):
    """LinkedIn organization page statistics including views across sections and devices."""

    date: dt.date = Field(description="The date of the record")
    organization: str = Field(description="The organization URN")
    about_page_views: int = Field(description="Number of page views on the About section")
    about_unique_page_views: int = Field(description="Number of unique page views on the About section")
    all_desktop_page_views: int = Field(description="Total page views on desktop")
    all_desktop_unique_page_views: int = Field(description="Total unique page views on desktop")
    all_mobile_page_views: int = Field(description="Total page views on mobile")
    all_mobile_unique_page_views: int = Field(description="Total unique page views on mobile")
    all_page_views: int = Field(description="Total page views")
    all_unique_page_views: int = Field(description="Total unique page views")
    careers_page_views: int = Field(description="Number of page views on the Careers section")
    careers_unique_page_views: int = Field(description="Number of unique page views on the Careers section")
    desktop_about_page_views: int = Field(description="Desktop page views for the About section")
    desktop_about_unique_page_views: int = Field(description="Desktop unique page views for the About section")
    desktop_careers_page_views: int = Field(description="Desktop page views for the Careers section")
    desktop_careers_unique_page_views: int = Field(description="Desktop unique page views for the Careers section")
    desktop_custom_button_click_counts: int = Field(description="Number of custom button clicks on desktop")
    desktop_insights_page_views: int = Field(description="Desktop page views for the Insights section")
    desktop_jobs_page_views: int = Field(description="Desktop page views for the Jobs section")
    desktop_jobs_unique_page_views: int = Field(description="Desktop unique page views for the Jobs section")
    desktop_life_at_page_views: int = Field(description="Desktop page views for the Life At section")
    desktop_overview_page_views: int = Field(description="Desktop page views for the Overview section")
    desktop_overview_unique_page_views: int = Field(description="Desktop unique page views for the Overview section")
    desktop_people_page_views: int = Field(description="Desktop page views for the People section")
    desktop_people_unique_page_views: int = Field(description="Desktop unique page views for the People section")
    desktop_products_page_views: int = Field(description="Desktop page views for the Products section")
    insights_page_views: int = Field(description="Number of page views on the Insights section")
    jobs_page_views: int = Field(description="Number of page views on the Jobs section")
    jobs_unique_page_views: int = Field(description="Number of unique page views on the Jobs section")
    life_at_page_views: int = Field(description="Number of page views on the Life At section")
    mobile_about_page_views: int = Field(description="Mobile page views for the About section")
    mobile_about_unique_page_views: int = Field(description="Mobile unique page views for the About section")
    mobile_careers_page_views: int = Field(description="Mobile page views for the Careers section")
    mobile_careers_unique_page_views: int = Field(description="Mobile unique page views for the Careers section")
    mobile_custom_button_click_counts: int = Field(description="Number of custom button clicks on mobile")
    mobile_insights_page_views: int = Field(description="Mobile page views for the Insights section")
    mobile_jobs_page_views: int = Field(description="Mobile page views for the Jobs section")
    mobile_jobs_unique_page_views: int = Field(description="Mobile unique page views for the Jobs section")
    mobile_life_at_page_views: int = Field(description="Mobile page views for the Life At section")
    mobile_overview_page_views: int = Field(description="Mobile page views for the Overview section")
    mobile_overview_unique_page_views: int = Field(description="Mobile unique page views for the Overview section")
    mobile_people_page_views: int = Field(description="Mobile page views for the People section")
    mobile_people_unique_page_views: int = Field(description="Mobile unique page views for the People section")
    mobile_products_page_views: int = Field(description="Mobile page views for the Products section")
    overview_page_views: int = Field(description="Number of page views on the Overview section")
    overview_unique_page_views: int = Field(description="Number of unique page views on the Overview section")
    people_page_views: int = Field(description="Number of page views on the People section")
    people_unique_page_views: int = Field(description="Number of unique page views on the People section")
    products_page_views: int = Field(description="Number of page views on the Products section")
    time_range_end: int = Field(description="The end time of the data range (epoch ms)")
    time_range_start: int = Field(description="The start time of the data range (epoch ms)")
