import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class AdsStats(Schema):
    account_descriptive_name: str | None = Field(default=None, description="The descriptive name of the account")
    account_id: int | None = Field(default=None, description="The account ID")
    ad_name: str | None = Field(default=None, description="The name of the ad")
    adgroup_id: int | None = Field(default=None, description="The ad group ID")
    adgroup_name: str | None = Field(default=None, description="The name of the ad group")
    adgroup_status: str | None = Field(default=None, description="The status of the ad group")
    all_conversions: int | None = Field(default=None, description="The total number of conversions")
    average_cost: int | None = Field(default=None, description="The average cost")
    average_cpc: int | None = Field(default=None, description="The average cost per click")
    average_cpm: int | None = Field(default=None, description="The average cost per thousand impressions")
    average_position: float | None = Field(default=None, description="The average position")
    campaign_id: int | None = Field(default=None, description="The campaign ID")
    campaign_name: str | None = Field(default=None, description="The name of the campaign")
    campaign_status: str | None = Field(default=None, description="The status of the campaign")
    clicks: int | None = Field(default=None, description="The total number of clicks")
    conversion_rate: float | None = Field(default=None, description="The conversion rate")
    conversions: int | None = Field(default=None, description="The total number of conversions")
    cost: int | None = Field(default=None, description="The total cost")
    cost_per_all_conversion: int | None = Field(default=None, description="The cost per all conversion")
    cost_per_conversion: int | None = Field(default=None, description="The cost per conversion")
    creative_final_mobile_url: str | None = Field(default=None, description="The final mobile URL of the creative")
    creative_final_url: str | None = Field(default=None, description="The final URL of the creative")
    creative_final_url_suffix: str | None = Field(default=None, description="The final URL suffix of the creative")
    ctr: float | None = Field(default=None, description="The click-through rate")
    date: dt.date | None = Field(default=None, description="The date of the data")
    description: str | None = Field(default=None, description="The description")
    display_url: str | None = Field(default=None, description="The display URL")
    headline: str | None = Field(default=None, description="The headline")
    id: int | None = Field(default=None, description="The ID")
    impressions: int | None = Field(default=None, description="The total number of impressions")
    interaction_rate: float | None = Field(default=None, description="The interaction rate")
    interactions: int | None = Field(default=None, description="The total number of interactions")
    path1: str | None = Field(default=None, description="The first path")
    path2: str | None = Field(default=None, description="The second path")
    view_through_conversions: int | None = Field(default=None, description="The total number of view-through conversions")
