# ###############
# PROJECT / UV
# ###############
[project]
name = "interloper-sql"
version = "0.1.0-alpha.1"
description = "Interloper SQL integration"
readme = "README.md"
authors = [{ name = "Guillaume Onfroy", email = "guillaume@digitlcloud.com" }]
requires-python = ">=3.10"
dependencies = [
    "interloper",
    "interloper-pandas",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.38",
]

[dependency-groups]
dev = ["pyright>=1.1.394", "ruff>=0.9.6"]

[tool.uv.sources]
interloper = { workspace = true }
interloper-pandas = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# ###############
# RUFF
# ###############
[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["E", "I", "UP", "ANN001", "ANN201", "ANN202"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"tests/**" = ["ANN", "F811"]

# ###############
# PYRIGHT
# ###############
[tool.pyright]
include = ["src"]
typeCheckingMode = "basic"
reportMissingParameterType = true
ignore = ["libs/**", "tests/**", "scripts/**"]
