API_SERVICE = "dfareporting"
API_VERSION = "v5"

SCOPES = [
    "https://www.googleapis.com/auth/dfareporting",
    "https://www.googleapis.com/auth/dfatrafficking",
]

CAMPAIGN_DIMENSIONS = [
    "date",
    "campaignStartDate",
    "campaignEndDate",
    "advertiserId",
    "advertiser",
    "campaignId",
    "campaign",
    "activityId",
    "activity",
    "dynamicProfile",
    "dynamicProfileId",
    "platformType",
]

CAMPAIGN_METRICS = [
    "impressions",
    "clicks",
    "clickRate",
    "activeViewViewableImpressions",
    "activeViewPercentageViewableImpressions",
    "activeViewMeasurableImpressions",
    "activeViewAverageViewableTimeSecond",
    "activeViewPercentVisibleAtCompletion",
    "plannedMediaCost",
    "mediaCost",
    "dv360CostUsd",
    "dv360Cost",
    "effectiveCpm",
    "totalConversions",
    "totalConversionsRevenue",
    "activityClickThroughConversions",
    "activityClickThroughRevenue",
    "activityViewThroughConversions",
    "activityViewThroughRevenue",
    "bookedActivities",
    "bookedClicks",
    "bookedImpressions",
    "bookedViewableImpressions",
    "richMediaVideoPlays",
    "richMediaAverageVideoViewTime",
    "richMediaVideoFirstQuartileCompletes",
    "richMediaVideoMidpoints",
    "richMediaVideoThirdQuartileCompletes",
    "richMediaVideoCompletions",
    "richMediaVideoCompanionClicks",
    "richMediaVideoViews",
    "videoCompanionImpressions",
    "videoCompanionClicks",
    "richMediaTrueViewViews",
]

AD_DIMENSIONS = [
    "date",
    "campaignStartDate",
    "campaignEndDate",
    "advertiserId",
    "advertiser",
    "campaignId",
    "campaign",
    "siteId",
    "site",
    "placementId",
    "placement",
    "packageRoadblockId",
    "packageRoadblock",
    "placementSize",
    "adId",
    "ad",
    "creativeId",
    "creative",
    "creativeType",
    "creativeSize",
    "placementRate",
    "packageRoadblockTotalBookedUnits",
    "placementCostStructure",
    "placementTotalBookedUnits",
    "activityId",
    "activity",
    "dynamicProfile",
    "dynamicProfileId",
    "platformType",
    "placementTotalPlannedMediaCost",
    "adStatus",
]

AD_METRICS = [
    "impressions",
    "clicks",
    "clickRate",
    "activeViewViewableImpressions",
    "activeViewPercentageViewableImpressions",
    "activeViewMeasurableImpressions",
    "activeViewAverageViewableTimeSecond",
    "activeViewPercentVisibleAtCompletion",
    "plannedMediaCost",
    "mediaCost",
    "dv360CostUsd",
    "dv360Cost",
    "effectiveCpm",
    "totalConversions",
    "totalConversionsRevenue",
    "activityClickThroughConversions",
    "activityClickThroughRevenue",
    "activityViewThroughConversions",
    "activityViewThroughRevenue",
    "bookedActivities",
    "bookedClicks",
    "bookedImpressions",
    "bookedViewableImpressions",
    "richMediaVideoPlays",
    "richMediaAverageVideoViewTime",
    "richMediaVideoFirstQuartileCompletes",
    "richMediaVideoMidpoints",
    "richMediaVideoThirdQuartileCompletes",
    "richMediaVideoCompletions",
    "richMediaVideoCompanionClicks",
    "richMediaVideoViews",
    "videoCompanionImpressions",
    "videoCompanionClicks",
    "richMediaTrueViewViews",
]

UNIQUE_REACH_DIMENSIONS = [
    "country",
    "campaignStartDate",
    "campaignEndDate",
    "advertiserId",
    "advertiser",
    "campaignId",
    "campaign",
]

UNIQUE_REACH_METRICS = [
    "impressions",
    "activeViewViewableImpressions",
    "activeViewMeasurableImpressions",
    "uniqueReachImpressionReach",
    "uniqueReachDuplicateImpressionReach",
    "uniqueReachExclusiveImpressionReach",
    "uniqueReachViewableImpressionReach",
    "uniqueReachTotalReach",
    "uniqueReachIncrementalImpressionReach",
    "uniqueReachIncrementalViewableImpressionReach",
    "uniqueReachIncrementalTotalReach",
]

# Minimum amount of time between polling requests (seconds).
MIN_RETRY_INTERVAL = 60

# Maximum amount of time between polling requests (seconds).
MAX_RETRY_INTERVAL = 20 * 60
