import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class Ads(Schema):
    """Ad-level performance report with core, additional, and conversion metrics."""

    id: str = Field(description="Unique identifier for the ad")
    type: str = Field(description="Type of the ad")
    granularity: str = Field(description="Granularity of the report")
    start_time: dt.datetime = Field(description="Start time of the reporting period")
    end_time: dt.datetime = Field(description="End time of the reporting period")
    impressions: int = Field(description="Number of times the ad was viewed")
    swipes: int = Field(description="Number of swipes")
    spend: int = Field(description="Total spend on the ad in micro-currency")
    quartile_1: int = Field(description="Viewers who watched the first 25% of the video")
    quartile_2: int = Field(description="Viewers who watched the first 50% of the video")
    quartile_3: int = Field(description="Viewers who watched the first 75% of the video")
    video_views: int = Field(description="Number of video views")
    view_completion: int = Field(description="Viewers who watched the entire video")
    view_time_millis: int = Field(description="Total view time in milliseconds")
    screen_time_millis: int = Field(description="Total screen time in milliseconds")
    android_installs: int = Field(description="Number of installs on Android devices")
    ios_installs: int = Field(description="Number of installs on iOS devices")
    attachment_avg_view_time_millis: int = Field(description="Average view time of attachments in milliseconds")
    attachment_frequency: float = Field(description="Frequency of attachment views")
    attachment_impressions: int = Field(description="Number of times the attachment was viewed")
    attachment_quartile_1: int = Field(description="Viewers who watched the first 25% of the attachment")
    attachment_quartile_2: int = Field(description="Viewers who watched the first 50% of the attachment")
    attachment_quartile_3: int = Field(description="Viewers who watched the first 75% of the attachment")
    attachment_total_view_time_millis: int = Field(description="Total view time of attachments in milliseconds")
    attachment_uniques: int = Field(description="Unique viewers of the attachment")
    attachment_video_views: int = Field(description="Number of video views within attachments")
    attachment_view_completion: int = Field(description="Viewers who watched the entire attachment")
    avg_screen_time_millis: int = Field(description="Average screen time in milliseconds")
    avg_view_time_millis: int = Field(description="Average view time in milliseconds")
    earned_impressions: int = Field(description="Number of earned impressions")
    earned_reach: int = Field(description="Number of earned reach")
    frequency: float = Field(description="Frequency of the ad views")
    native_leads: int = Field(description="Number of native leads generated")
    paid_impressions: int = Field(description="Number of paid impressions")
    play_time_millis: int = Field(description="Total play time in milliseconds")
    profile_clicks: int = Field(description="Number of profile clicks")
    saves: int = Field(description="Number of saves")
    shares: int = Field(description="Number of shares")
    story_completes: int = Field(description="Number of story completes")
    story_opens: int = Field(description="Number of story opens")
    swipe_up_percent: float = Field(description="Percentage of swipes up")
    total_impressions: int = Field(description="Total number of impressions")
    total_installs: int = Field(description="Total number of installs")
    total_reach: int = Field(description="Total reach of the ad")
    uniques: int = Field(description="Unique viewers of the ad")
    video_views_15s: int = Field(description="Number of 15-second video views")
    video_views_time_based: int = Field(description="Number of video views based on time duration")
    conversion_purchases: int = Field(description="Number of purchase conversions")
    conversion_purchases_value: int = Field(description="Total value of purchase conversions")
    conversion_save: int = Field(description="Number of save conversions")
    conversion_start_checkout: int = Field(description="Number of start checkout conversions")
    conversion_add_cart: int = Field(description="Number of add to cart conversions")
    conversion_view_content: int = Field(description="Number of view content conversions")
    conversion_add_billing: int = Field(description="Number of add billing conversions")
    conversion_sign_ups: int = Field(description="Number of sign up conversions")
    conversion_searches: int = Field(description="Number of search conversions")
    conversion_level_completes: int = Field(description="Number of level complete conversions")
    conversion_app_opens: int = Field(description="Number of app open conversions")
    conversion_page_views: int = Field(description="Number of page view conversions")
    conversion_subscribe: int = Field(description="Number of subscribe conversions")
    conversion_ad_click: int = Field(description="Number of ad click conversions")
    conversion_ad_view: int = Field(description="Number of ad view conversions")
    conversion_complete_tutorial: int = Field(description="Number of tutorial completion conversions")
    conversion_invite: int = Field(description="Number of invite conversions")
    conversion_login: int = Field(description="Number of login conversions")
    conversion_share: int = Field(description="Number of share conversions")
    conversion_reserve: int = Field(description="Number of reserve conversions")
    conversion_achievement_unlocked: int = Field(description="Number of achievement unlock conversions")
    conversion_add_to_wishlist: int = Field(description="Number of add to wishlist conversions")
    conversion_spend_credits: int = Field(description="Number of spend credit conversions")
    conversion_rate: int = Field(description="Conversion rate percentage")
    conversion_start_trial: int = Field(description="Number of start trial conversions")
    conversion_list_view: int = Field(description="Number of list view conversions")
    conversion_visit: int = Field(description="Number of visit conversions")
    custom_event_1: int = Field(description="Custom event 1")
    custom_event_2: int = Field(description="Custom event 2")
    custom_event_3: int = Field(description="Custom event 3")
    custom_event_4: int = Field(description="Custom event 4")
    custom_event_5: int = Field(description="Custom event 5")
