
from interloper.schema import Schema
from pydantic import Field


class AdsByCountry(Schema):
    """Ad performance report segmented by country with delivery and conversion metrics."""

    id: str = Field(description="Unique identifier for the ad")
    type: str = Field(description="Type of the ad")
    granularity: str = Field(description="Granularity of the report")
    start_time: str = Field(description="Start time of the reporting period")
    end_time: str = Field(description="End time of the reporting period")
    country: str = Field(description="Country where the ad was displayed")
    impressions: int = Field(description="Number of times the ad was displayed")
    swipes: int = Field(description="Number of swipes on the ad")
    spend: int = Field(description="Amount spent on the ad in micro-currency")
    quartile_1: float = Field(description="Viewers who watched at least 25% of the ad")
    quartile_2: float = Field(description="Viewers who watched at least 50% of the ad")
    quartile_3: float = Field(description="Viewers who watched at least 75% of the ad")
    view_completion: int = Field(description="Viewers who watched the entire ad")
    video_views: int = Field(description="Number of video views")
    attachment_quartile_1: int = Field(description="Viewers who watched 25% of the attachment")
    attachment_quartile_2: int = Field(description="Viewers who watched 50% of the attachment")
    attachment_quartile_3: int = Field(description="Viewers who watched 75% of the attachment")
    attachment_view_completion: int = Field(description="Viewers who watched the entire attachment")
    attachment_total_view_time_millis: float = Field(description="Total view time of attachments in milliseconds")
    attachment_video_views: int = Field(description="Number of video views within attachments")
    story_opens: int = Field(description="Number of story opens")
    story_completes: int = Field(description="Number of story completes")
    shares: int = Field(description="Number of shares")
    saves: int = Field(description="Number of saves")
    total_installs: int = Field(description="Total number of app installs")
    conversion_purchases: int = Field(description="Number of purchase conversions")
    conversion_purchases_value: int = Field(description="Total value of purchase conversions")
    conversion_save: int = Field(description="Number of save conversions")
    conversion_start_checkout: int = Field(description="Number of start checkout conversions")
    conversion_add_cart: int = Field(description="Number of add to cart conversions")
    conversion_view_content: int = Field(description="Number of view content conversions")
    conversion_add_billing: int = Field(description="Number of add billing conversions")
    conversion_sign_ups: int = Field(description="Number of sign up conversions")
    conversion_searches: int = Field(description="Number of search conversions")
    conversion_level_completes: int = Field(description="Number of level complete conversions")
    conversion_app_opens: int = Field(description="Number of app open conversions")
    conversion_page_views: int = Field(description="Number of page view conversions")
    conversion_subscribe: int = Field(description="Number of subscribe conversions")
    conversion_ad_click: int = Field(description="Number of ad click conversions")
    conversion_ad_view: int = Field(description="Number of ad view conversions")
    conversion_complete_tutorial: int = Field(description="Number of tutorial completion conversions")
    conversion_invite: int = Field(description="Number of invite conversions")
    conversion_login: int = Field(description="Number of login conversions")
    conversion_share: int = Field(description="Number of share conversions")
    conversion_reserve: int = Field(description="Number of reserve conversions")
    conversion_achievement_unlocked: int = Field(description="Number of achievement unlock conversions")
    conversion_add_to_wishlist: int = Field(description="Number of add to wishlist conversions")
    conversion_spend_credits: int = Field(description="Number of spend credit conversions")
    conversion_rate: int = Field(description="Conversion rate")
    conversion_start_trial: int = Field(description="Number of start trial conversions")
    conversion_list_view: int = Field(description="Number of list view conversions")
    conversion_visit: int = Field(description="Number of visit conversions")
    custom_event_1: int = Field(description="Custom event 1")
    custom_event_2: int = Field(description="Custom event 2")
    custom_event_3: int = Field(description="Custom event 3")
    custom_event_4: int = Field(description="Custom event 4")
    custom_event_5: int = Field(description="Custom event 5")
