import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class AdsStatsByCountry(Schema):
    """The Ads by Country report provides insights into ad performance based on different countries. It includes key metrics such as attachment total view time, various conversion events (e.g., ad clicks, purchases, sign-ups), custom events, impressions, quartiles of ad views, saves, shares, spend, swipes, total installs, ad type, video views, and view completion rate."""

    attachment_total_view_time_millis: float | None = Field(default=None, description="The total view time of attachments in milliseconds")
    conversion_achievement_unlocked: int | None = Field(default=None, description="The number of achievements unlocked attributed to the ad")
    conversion_ad_click: int | None = Field(default=None, description="The number of ad clicks attributed to the ad")
    conversion_ad_view: int | None = Field(default=None, description="The number of ad views attributed to the ad")
    conversion_add_billing: int | None = Field(default=None, description="The number of users who added billing information attributed to the ad")
    conversion_add_cart: int | None = Field(default=None, description="The number of users who added items to the cart attributed to the ad")
    conversion_add_to_wishlist: int | None = Field(default=None, description="The number of items added to the wishlist attributed to the ad")
    conversion_app_opens: int | None = Field(default=None, description="The number of app opens attributed to the ad")
    conversion_complete_tutorial: int | None = Field(default=None, description="The number of users who completed a tutorial attributed to the ad")
    conversion_invite: int | None = Field(default=None, description="The number of invites sent attributed to the ad")
    conversion_level_completes: int | None = Field(default=None, description="The number of users who completed a level attributed to the ad")
    conversion_list_view: int | None = Field(default=None, description="The number of list views attributed to the ad")
    conversion_login: int | None = Field(default=None, description="The number of logins attributed to the ad")
    conversion_page_views: int | None = Field(default=None, description="The number of page views attributed to the ad")
    conversion_purchases: int | None = Field(default=None, description="The number of purchases attributed to the ad")
    conversion_purchases_value: int | None = Field(default=None, description="The total value of purchases attributed to the ad")
    conversion_rate: int | None = Field(default=None, description="The conversion rate of the ad")
    conversion_reserve: int | None = Field(default=None, description="The number of reservations attributed to the ad")
    conversion_save: int | None = Field(default=None, description="The number of saves attributed to the ad")
    conversion_searches: int | None = Field(default=None, description="The number of searches attributed to the ad")
    conversion_share: int | None = Field(default=None, description="The number of shares attributed to the ad")
    conversion_sign_ups: int | None = Field(default=None, description="The number of sign-ups attributed to the ad")
    conversion_spend_credits: int | None = Field(default=None, description="The number of credits spent attributed to the ad")
    conversion_start_checkout: int | None = Field(default=None, description="The number of users who started the checkout process attributed to the ad")
    conversion_start_trial: int | None = Field(default=None, description="The number of users who started a trial attributed to the ad")
    conversion_subscribe: int | None = Field(default=None, description="The number of subscriptions attributed to the ad")
    conversion_view_content: int | None = Field(default=None, description="The number of users who viewed content attributed to the ad")
    conversion_visit: int | None = Field(default=None, description="The number of visits to the conversion page attributed to the ad")
    country: str | None = Field(default=None, description="The country where the ad was displayed")
    custom_event_1: int | None = Field(default=None, description="The number of custom event 1 attributed to the ad")
    custom_event_2: int | None = Field(default=None, description="The number of custom event 2 attributed to the ad")
    custom_event_3: int | None = Field(default=None, description="The number of custom event 3 attributed to the ad")
    custom_event_4: int | None = Field(default=None, description="The number of custom event 4 attributed to the ad")
    custom_event_5: int | None = Field(default=None, description="The number of custom event 5 attributed to the ad")
    end_time: str | None = Field(default=None, description="The end time of the ad")
    granularity: str | None = Field(default=None, description="The level of granularity for the ad data")
    id: str | None = Field(default=None, description="The unique identifier of the ad")
    impressions: int | None = Field(default=None, description="The number of times the ad was displayed")
    quartile_1: float | None = Field(default=None, description="The percentage of users who viewed at least 25% of the ad")
    quartile_2: float | None = Field(default=None, description="The percentage of users who viewed at least 50% of the ad")
    quartile_3: float | None = Field(default=None, description="The percentage of users who viewed at least 75% of the ad")
    saves: int | None = Field(default=None, description="The number of times the ad was saved")
    shares: int | None = Field(default=None, description="The number of times the ad was shared")
    spend: int | None = Field(default=None, description="The amount spent on the ad")
    start_time: str | None = Field(default=None, description="The start time of the ad")
    swipes: int | None = Field(default=None, description="The number of swipes on the ad")
    total_installs: int | None = Field(default=None, description="The total number of app installs attributed to the ad")
    type: str | None = Field(default=None, description="The type of the ad")
    video_views: int | None = Field(default=None, description="The number of times the video ad was viewed")
    view_completion: int | None = Field(default=None, description="The percentage of users who viewed the entire ad")
    story_completes: int | None = Field(default=None, description="The amount of completes for the story ad")
    date: dt.date | None = Field(default=None, description="Partition date")
