import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class AdsStats(Schema):
    """The Ads report provides insights on the performance of individual ads in a campaign. It includes key metrics such as attachment views, conversions, custom events, impressions, saves, shares, spend, story opens, swipes, and video views"""

    android_installs: int | None = Field(default=None, description="Number of installs on Android devices")
    attachment_avg_view_time_millis: int | None = Field(default=None, description="Average view time of attachments in milliseconds")
    attachment_frequency: float | None = Field(default=None, description="Frequency of attachment views")
    attachment_impressions: int | None = Field(default=None, description="Number of times the attachment was viewed")
    attachment_quartile_1: int | None = Field(default=None, description="Number of viewers who watched the first 25% of the attachment")
    attachment_quartile_2: int | None = Field(default=None, description="Number of viewers who watched the first 50% of the attachment")
    attachment_quartile_3: int | None = Field(default=None, description="Number of viewers who watched the first 75% of the attachment")
    attachment_total_view_time_millis: int | None = Field(default=None, description="Total view time of attachments in milliseconds")
    attachment_uniques: int | None = Field(default=None, description="Unique viewers of the attachment")
    attachment_video_views: int | None = Field(default=None, description="Number of video views within attachments")
    attachment_view_completion: int | None = Field(default=None, description="Number of viewers who watched the entire attachment")
    avg_screen_time_millis: int | None = Field(default=None, description="Average screen time in milliseconds")
    avg_view_time_millis: int | None = Field(default=None, description="Average view time in milliseconds")
    conversion_achievement_unlocked: int | None = Field(default=None, description="Number of achievement unlock conversions")
    conversion_ad_click: int | None = Field(default=None, description="Number of ad click conversions")
    conversion_ad_view: int | None = Field(default=None, description="Number of ad view conversions")
    conversion_add_billing: int | None = Field(default=None, description="Number of add billing conversions")
    conversion_add_cart: int | None = Field(default=None, description="Number of add to cart conversions")
    conversion_add_to_wishlist: int | None = Field(default=None, description="Number of add to wishlist conversions")
    conversion_app_opens: int | None = Field(default=None, description="Number of app open conversions")
    conversion_complete_tutorial: int | None = Field(default=None, description="Number of tutorial completion conversions")
    conversion_invite: int | None = Field(default=None, description="Number of invite conversions")
    conversion_level_completes: int | None = Field(default=None, description="Number of level complete conversions")
    conversion_list_view: int | None = Field(default=None, description="Number of list view conversions")
    conversion_login: int | None = Field(default=None, description="Number of login conversions")
    conversion_page_views: int | None = Field(default=None, description="Number of page view conversions")
    conversion_purchases: int | None = Field(default=None, description="Number of purchase conversions")
    conversion_purchases_value: int | None = Field(default=None, description="Total value of purchase conversions")
    conversion_rate: int | None = Field(default=None, description="Conversion rate percentage")
    conversion_reserve: int | None = Field(default=None, description="Number of reserve conversions")
    conversion_save: int | None = Field(default=None, description="Number of save conversions")
    conversion_searches: int | None = Field(default=None, description="Number of search conversions")
    conversion_share: int | None = Field(default=None, description="Number of share conversions")
    conversion_sign_ups: int | None = Field(default=None, description="Number of sign up conversions")
    conversion_spend_credits: int | None = Field(default=None, description="Number of spend credit conversions")
    conversion_start_checkout: int | None = Field(default=None, description="Number of start checkout conversions")
    conversion_start_trial: int | None = Field(default=None, description="Number of start trial conversions")
    conversion_subscribe: int | None = Field(default=None, description="Number of subscribe conversions")
    conversion_view_content: int | None = Field(default=None, description="Number of view content conversions")
    conversion_visit: int | None = Field(default=None, description="Number of visit conversions")
    custom_event_1: int | None = Field(default=None, description="Custom event 1")
    custom_event_2: int | None = Field(default=None, description="Custom event 2")
    custom_event_3: int | None = Field(default=None, description="Custom event 3")
    custom_event_4: int | None = Field(default=None, description="Custom event 4")
    custom_event_5: int | None = Field(default=None, description="Custom event 5")
    earned_impressions: int | None = Field(default=None, description="Number of earned impressions")
    earned_reach: int | None = Field(default=None, description="Number of earned reach")
    end_time: dt.datetime | None = Field(default=None, description="End time of the reporting period")
    frequency: float | None = Field(default=None, description="Frequency of the ad views")
    granularity: str | None = Field(default=None, description="Granularity of the report (e.g., daily, weekly)")
    id: str | None = Field(default=None, description="Unique identifier for the ad")
    impressions: int | None = Field(default=None, description="Number of times the ad was viewed")
    ios_installs: int | None = Field(default=None, description="Number of installs on iOS devices")
    native_leads: int | None = Field(default=None, description="Number of native leads generated")
    paid_impressions: int | None = Field(default=None, description="Number of paid impressions")
    play_time_millis: int | None = Field(default=None, description="Total play time in milliseconds")
    profile_clicks: int | None = Field(default=None, description="Number of profile clicks")
    quartile_1: int | None = Field(default=None, description="Number of viewers who watched the first 25% of the video")
    quartile_2: int | None = Field(default=None, description="Number of viewers who watched the first 50% of the video")
    quartile_3: int | None = Field(default=None, description="Number of viewers who watched the first 75% of the video")
    saves: int | None = Field(default=None, description="Number of saves")
    screen_time_millis: int | None = Field(default=None, description="Total screen time in milliseconds")
    shares: int | None = Field(default=None, description="Number of shares")
    spend: int | None = Field(default=None, description="Total spend on the ad")
    start_time: dt.datetime | None = Field(default=None, description="Start time of the reporting period")
    story_completes: int | None = Field(default=None, description="Number of story completes")
    story_opens: int | None = Field(default=None, description="Number of story opens")
    swipe_up_percent: float | None = Field(default=None, description="Percentage of swipes up")
    swipes: int | None = Field(default=None, description="Number of swipes")
    total_impressions: int | None = Field(default=None, description="Total number of impressions")
    total_installs: int | None = Field(default=None, description="Total number of installs")
    total_reach: int | None = Field(default=None, description="Total reach of the ad")
    type: str | None = Field(default=None, description="Type of the ad")
    uniques: int | None = Field(default=None, description="Unique viewers of the ad")
    video_views: int | None = Field(default=None, description="Number of video views")
    video_views_15s: int | None = Field(default=None, description="Number of 15-second video views")
    video_views_time_based: int | None = Field(default=None, description="Number of video views based on time duration")
    view_completion: int | None = Field(default=None, description="Number of viewers who watched the entire video")
    view_time_millis: int | None = Field(default=None, description="Total view time in milliseconds")
    date: dt.date | None = Field(default=None, description="Partition date")
