import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class AdsStats(Schema):
    """Ad-level performance metrics including placement, creative, and media cost details."""

    active_view_average_viewable_time_seconds: float | None = Field(description="Active View average viewable time in seconds")
    active_view_measurable_impressions: int | None = Field(description="Active View measurable impressions")
    active_view_pct_viewable_impressions: float | None = Field(description="Active View percentage of viewable impressions")
    active_view_pct_visible_at_completion: float | None = Field(description="Active View percentage visible at completion")
    active_view_viewable_impressions: int | None = Field(description="Active View viewable impressions")
    activity: str | None = Field(description="Activity name")
    activity_id: str | None = Field(description="Activity ID")
    ad: str | None = Field(description="Ad name")
    ad_id: str | None = Field(description="Ad ID")
    ad_status: str | None = Field(description="Ad status")
    advertiser: str | None = Field(description="Name of the advertiser")
    advertiser_id: str | None = Field(description="ID of the advertiser")
    booked_activities: float | None = Field(description="Booked activities")
    booked_clicks: float | None = Field(description="Booked clicks")
    booked_impressions: float | None = Field(description="Booked impressions")
    booked_viewable_impressions: float | None = Field(description="Booked viewable impressions")
    campaign: str | None = Field(description="Name of the campaign")
    campaign_end_date: dt.date | None = Field(description="End date of the campaign")
    campaign_id: str | None = Field(description="ID of the campaign")
    campaign_start_date: dt.date | None = Field(description="Start date of the campaign")
    click_rate: float | None = Field(description="Click rate")
    click_through_conversions: float | None = Field(description="Click-through conversions")
    click_through_revenue: float | None = Field(description="Click-through revenue")
    clicks: int | None = Field(description="Number of clicks")
    companion_clicks: int | None = Field(description="Companion clicks")
    companion_views: int | None = Field(description="Companion views")
    creative: str | None = Field(description="Creative name")
    creative_id: str | None = Field(description="Creative ID")
    creative_pixel_size: str | None = Field(description="Pixel size of the creative")
    creative_type: str | None = Field(description="Creative type")
    date: dt.date | None = Field(description="Date of the ad report")
    dv_360_cost_account_currency: float | None = Field(description="DV 360 cost in account currency")
    dv_360_cost_usd: float | None = Field(description="DV 360 cost in USD")
    dynamic_profile: str | None = Field(description="Dynamic profile")
    dynamic_profile_id: str | None = Field(description="Dynamic profile ID")
    effective_cpm: float | None = Field(description="Effective CPM")
    impressions: int | None = Field(description="Number of impressions")
    media_cost: float | None = Field(description="Media cost")
    package_roadblock: str | None = Field(description="Name of the package roadblock")
    package_roadblock_id: str | None = Field(description="ID of the package roadblock")
    package_roadblock_total_booked_units: str | None = Field(description="Package roadblock total booked units")
    placement: str | None = Field(description="Name of the placement")
    placement_cost_structure: str | None = Field(description="Placement cost structure")
    placement_id: str | None = Field(description="ID of the placement")
    placement_pixel_size: str | None = Field(description="Pixel size of the placement")
    placement_rate: str | None = Field(description="Placement rate")
    placement_total_booked_units: str | None = Field(description="Placement total booked units")
    placement_total_planned_media_cost: str | None = Field(description="Placement total planned media cost")
    planned_media_cost: float | None = Field(description="Planned media cost")
    platform_type: str | None = Field(description="Platform type")
    site_cm_360: str | None = Field(description="Name of the site in Campaign Manager 360")
    site_id_cm_360: str | None = Field(description="ID of the site in Campaign Manager 360")
    total_conversions: float | None = Field(description="Total conversions")
    total_revenue: float | None = Field(description="Total revenue")
    true_view_views: int | None = Field(description="TrueView views")
    video_average_view_time: float | None = Field(description="Video average view time")
    video_companion_clicks: int | None = Field(description="Video companion clicks")
    video_completions: int | None = Field(description="Video completions")
    video_first_quartile_completions: int | None = Field(description="Video first quartile completions")
    video_midpoints: int | None = Field(description="Video midpoints")
    video_plays: int | None = Field(description="Video plays")
    video_third_quartile_completions: int | None = Field(description="Video third quartile completions")
    video_views: int | None = Field(description="Video views")
    view_through_conversions: float | None = Field(description="View-through conversions")
    view_through_revenue: float | None = Field(description="View-through revenue")
