# ###############
# PROJECT / UV
# ###############
[project]
name = "interloper-sqlite"
version = "0.0.0"
description = "Interloper SQLite integration"
readme = "README.md"
authors = [{ name = "Guillaume Onfroy", email = "guillaume@digitlcloud.com" }]
requires-python = ">=3.10"
dependencies = ["interloper"]

[dependency-groups]
dev = ["pyright>=1.1.394", "ruff>=0.9.6"]

[tool.uv.sources]
interloper = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


# ###############
# RUFF
# ###############
[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["E", "I", "UP", "ANN001", "ANN201", "ANN202"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"tests/**" = ["ANN", "F811"]

# ###############
# PYRIGHT
# ###############
[tool.pyright]
include = ["src"]
typeCheckingMode = "basic"
reportMissingParameterType = true
ignore = ["libs/**", "tests/**", "scripts/**"]
