# ###############
# PROJECT
# ###############
[project]
name = "interloper-google-cloud"
version = "0.1.0"
description = "Interloper Google Cloud integration"
readme = "README.md"
authors = [{ name = "Guillaume Onfroy", email = "guillaume@digitlcloud.com" }]
requires-python = ">=3.10"
dependencies = [
    "google-cloud-bigquery>=3.31.0",
    "interloper",
    "interloper-pandas",
    "pandas-gbq>=0.28.0",
]

[dependency-groups]
dev = ["pyright>=1.1.394", "pytest>=8.3.5", "ruff>=0.9.6"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# ###############
# UV
# ###############
[tool.uv.sources]
interloper = { workspace = true }
interloper-pandas = { workspace = true }

# ###############
# RUFF
# ###############
[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["E", "I", "UP", "ANN001", "ANN201", "ANN202"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"tests/**" = ["ANN"]

# ###############
# PYRIGHT
# ###############
[tool.pyright]
include = ["src"]
typeCheckingMode = "basic"
reportMissingParameterType = true
ignore = ["libs/**", "tests/**", "scripts/**"]
