BASE_URL = "https://api.linkedin.com/rest"
API_URL = "https://api.linkedin.com"
AUTH_BASE_URL = "https://www.linkedin.com"
TOKEN_ENDPOINT = "/oauth/v2/accessToken"
LINKEDIN_VERSION = "202506"
RESTLI_PROTOCOL_VERSION = "2.0.0"
