BASE_URL = "https://business-api.tiktok.com/open_api/v1.3"

PAGE_SIZE = 200

# Max paginated requests in flight at once per asset. Bounds fan-out so a
# many-page report can't stampede TikTok into rate limits.
PAGE_CONCURRENCY = 8

ATTRIBUTE_METRICS = [
    "campaign_name",
    "campaign_id",
    "objective_type",
    "split_test",
    "campaign_budget",
    "campaign_dedicate_type",
    "app_promotion_type",
    "adgroup_name",
    "adgroup_id",
    "placement_type",
    "promotion_type",
    "opt_status",
    "dpa_target_audience_type",
    "budget",
    "smart_target",
    "pricing_category",
    "bid_strategy",
    "bid",
    "aeo_type",
    "ad_name",
    "ad_text",
    "call_to_action",
    "tt_app_id",
    "tt_app_name",
    "mobile_app_id",
]

BASIC_METRICS = [
    "campaign_name",
    "campaign_id",
    "adgroup_name",
    "adgroup_id",
    "ad_name",
    "ad_text",
    "spend",
    "complete_payment",
    "total_complete_payment_rate",
    "vta_complete_payment",
    "vta_complete_payment_value",
    "cpc",
    "cpm",
    "impressions",
    "gross_impressions",
    "clicks",
    "ctr",
    "reach",
    "cost_per_1000_reached",
    "conversion",
    "cost_per_conversion",
    "conversion_rate",
    "real_time_conversion",
    "real_time_cost_per_conversion",
    "real_time_conversion_rate",
    "result",
    "cost_per_result",
    "result_rate",
    "real_time_result",
    "real_time_cost_per_result",
    "real_time_result_rate",
    "secondary_goal_result",
    "cost_per_secondary_goal_result",
    "secondary_goal_result_rate",
    "frequency",
    "currency",
]

AUDIENCE_METRICS = [
    "campaign_name",
    "campaign_id",
    "ad_name",
    "spend",
    "cpc",
    "cpm",
    "impressions",
    "gross_impressions",
    "clicks",
    "ctr",
    "conversion",
    "cost_per_conversion",
    "conversion_rate",
    "real_time_conversion",
    "real_time_cost_per_conversion",
    "real_time_conversion_rate",
    "result",
    "cost_per_result",
    "result_rate",
    "real_time_result",
    "real_time_cost_per_result",
    "real_time_result_rate",
    "currency",
]

VIDEO_METRICS = [
    "campaign_name",
    "campaign_id",
    "adgroup_name",
    "adgroup_id",
    "ad_name",
    "ad_text",
    "spend",
    "impressions",
    "gross_impressions",
    "clicks",
    "ctr",
    "reach",
    "frequency",
    "currency",
    "follows",
    "likes",
    "shares",
    "comments",
    "profile_visits_rate",
    "profile_visits",
    "clicks_on_music_disc",
    "video_play_actions",
    "video_watched_2s",
    "video_watched_6s",
    "average_video_play",
    "average_video_play_per_user",
    "video_views_p25",
    "video_views_p50",
    "video_views_p75",
    "video_views_p100",
    "engaged_view",
    "engaged_view_15s",
]

INTERACTIVE_METRICS = [
    "interactive_add_on_impressions",
    "interactive_add_on_destination_clicks",
    "interactive_add_on_activity_clicks",
    "interactive_add_on_option_a_clicks",
    "interactive_add_on_option_b_clicks",
    "countdown_sticker_recall_clicks",
]

LIVE_METRICS = [
    "live_views",
    "live_unique_views",
    "live_effective_views",
    "live_product_clicks",
]

ADVERTISER_FIELDS = [
    "address",
    "advertiser_id",
    "balance",
    "company",
    "country",
    "create_time",
    "currency",
    "description",
    "display_timezone",
    "industry",
    "language",
    "license_no",
    "license_url",
    "name",
    "owner_bc_id",
    "rejection_reason",
    "role",
    "status",
    "timezone",
]
