"""Interloper's public API: assets, sources, destinations, DAGs, and runners."""

from interloper.asset import Asset, AssetDefinition, ExecutionContext, Upstream, asset
from interloper.catalog import Catalog
from interloper.component import (
    KINDS,
    Component,
    ComponentDefinition,
    ComponentIdentity,
    Relation,
)
from interloper.config import Config, config
from interloper.connection import (
    Connection,
    ConnectionState,
    OAuthConnection,
    RefreshTokenOAuthConnection,
    Renewal,
    connection,
)
from interloper.dag import DAG
from interloper.destination import (
    CSVDestination,
    Destination,
    DestinationDefinition,
    FileDestination,
    IOContext,
    MemoryDestination,
    destination,
)
from interloper.events import Event, EventBus, EventType
from interloper.hook import HOOK_EVENT_TYPES, Hook, HookContext, HookState, TriggerHook, WebhookHook
from interloper.job import CronJob, Job, JobState
from interloper.normalizer import MaterializationStrategy, Normalizer
from interloper.oauth import OAuthConfig, OAuthProvider, RefreshTokenResponse
from interloper.operation import Operation, OperationContext, OperationResult, Workload
from interloper.partitioning import (
    Partition,
    PartitionConfig,
    PartitionWindow,
    TimeGranularity,
    TimePartition,
    TimePartitionConfig,
    TimePartitionWindow,
)
from interloper.registry import Registry
from interloper.resource import Resource, ResourceDefinition
from interloper.resource.fields import (
    CronField,
    FetchField,
    InputField,
    JsonField,
    SecretField,
    SelectField,
    TextField,
    TimezoneField,
    fetch_field_provider,
    is_fetch_field_provider,
)
from interloper.rest import (
    AsyncRESTClient,
    BasePaginator,
    HeaderLinkPaginator,
    HTTPBearerAuth,
    JSONCursorPaginator,
    JSONLinkPaginator,
    OAuth2Auth,
    OAuth2ClientCredentialsAuth,
    OAuth2RefreshTokenAuth,
    OffsetPaginator,
    PageNumberPaginator,
    RangePaginator,
    RESTClient,
    SinglePagePaginator,
)
from interloper.runner import AsyncRunner, MultiProcessRunner, Runner, RunResult, SerialRunner
from interloper.schema import Schema, schema
from interloper.serializable import Serializable, Spec
from interloper.source import Source, SourceDefinition, source
from interloper.utils import bounded_gather, run

__all__ = [
    "DAG",
    "HOOK_EVENT_TYPES",
    "KINDS",
    "Asset",
    "AssetDefinition",
    "AsyncRESTClient",
    "AsyncRunner",
    "BasePaginator",
    "CSVDestination",
    "Catalog",
    "Component",
    "ComponentDefinition",
    "ComponentIdentity",
    "Config",
    "Connection",
    "ConnectionState",
    "CronField",
    "CronJob",
    "Destination",
    "DestinationDefinition",
    "Event",
    "EventBus",
    "EventType",
    "ExecutionContext",
    "FetchField",
    "FileDestination",
    "HTTPBearerAuth",
    "HeaderLinkPaginator",
    "Hook",
    "HookContext",
    "HookState",
    "IOContext",
    "InputField",
    "JSONCursorPaginator",
    "JSONLinkPaginator",
    "Job",
    "JobState",
    "JsonField",
    "MaterializationStrategy",
    "MemoryDestination",
    "MultiProcessRunner",
    "Normalizer",
    "OAuth2Auth",
    "OAuth2ClientCredentialsAuth",
    "OAuth2RefreshTokenAuth",
    "OAuthConfig",
    "OAuthConnection",
    "OAuthProvider",
    "OffsetPaginator",
    "Operation",
    "OperationContext",
    "OperationResult",
    "PageNumberPaginator",
    "Partition",
    "PartitionConfig",
    "PartitionWindow",
    "RESTClient",
    "RangePaginator",
    "RefreshTokenOAuthConnection",
    "RefreshTokenResponse",
    "Registry",
    "Relation",
    "Renewal",
    "Resource",
    "ResourceDefinition",
    "RunResult",
    "Runner",
    "Schema",
    "SecretField",
    "SelectField",
    "SerialRunner",
    "Serializable",
    "SinglePagePaginator",
    "Source",
    "SourceDefinition",
    "Spec",
    "TextField",
    "TimeGranularity",
    "TimePartition",
    "TimePartitionConfig",
    "TimePartitionWindow",
    "TimezoneField",
    "TriggerHook",
    "Upstream",
    "WebhookHook",
    "Workload",
    "asset",
    "bounded_gather",
    "config",
    "connection",
    "destination",
    "fetch_field_provider",
    "is_fetch_field_provider",
    "run",
    "schema",
    "source",
]
