on:
  workflow_call:
    inputs:
      ruff:
        type: boolean
        required: false
        default: false
      pyright:
        type: boolean
        required: false
        default: false
      pytest:
        type: boolean
        required: false
        default: false

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    permissions:
      contents: "write"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: UV setup
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: "3.10"

      - name: UV sync
        run: uv sync --all-packages --all-extras

      - name: Ruff
        if: inputs.ruff == true
        run: uv run ruff check .

      - name: Pyright
        if: inputs.pyright == true
        run: uv run pyright

      - name: Pytest
        if: inputs.pytest == true
        run: uv run pytest
