name: Check & Release

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  checks:
    uses: ./.github/workflows/_checks.yaml

  release:
    uses: ./.github/workflows/_release.yaml
    if: github.ref_name == 'main' || github.ref_name == 'rc' || github.ref_name == 'alpha'
    needs: checks
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
