name: "Lint PR"

on:
  pull_request:

permissions:
  pull-requests: read
  statuses: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    if: github.ref_name != 'main' && github.ref_name != 'rc' && github.ref_name != 'alpha'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          # TODO: list dynamically from `packages` directory
          scopes: |
            core
            assets
            duckdb
            google-cloud
            pandas
            sql
          requireScope: true
