name: "Lint PR"

on:
  # pull_request:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

permissions:
  pull-requests: read
  statuses: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
  
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          scopes: |
            core
            assets
            duckdb
            google-cloud
            pandas
            sql
          requireScope: true
