import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class AdsReport(Schema):
    """Facebook Ads ad-level insights with performance metrics, engagement actions, and cost breakdowns."""

    account_currency: str = Field(description="The currency used for the account")
    account_id: str = Field(description="Identifier for the account")
    account_name: str = Field(description="Name of the account")
    action_values_offsite_conversion_fb_pixel_purchase: float | None = Field(default=None, description="Value of offsite conversions tracked through the Facebook pixel for purchases")
    actions_comment: int | None = Field(default=None, description="Number of comments on posts or ads")
    actions_landing_page_view: int | None = Field(default=None, description="Number of landing page views")
    actions_link_click: int | None = Field(default=None, description="Number of link clicks")
    actions_offsite_conversion_fb_pixel_lead: int | None = Field(default=None, description="Offsite conversion (Facebook Pixel) - Leads")
    actions_offsite_conversion_fb_pixel_purchase: int | None = Field(default=None, description="Offsite conversion (Facebook Pixel) - Purchases")
    actions_onsite_conversion_post_save: int | None = Field(default=None, description="Number of onsite conversion post saves")
    actions_page_engagement: int | None = Field(default=None, description="Number of page engagements")
    actions_post: int | None = Field(default=None, description="Number of post actions")
    actions_post_engagement: int | None = Field(default=None, description="Number of post engagements")
    actions_post_reaction: int | None = Field(default=None, description="Number of post reactions")
    actions_video_view: int | None = Field(default=None, description="Number of video views")
    ad_id: str = Field(description="Identifier for the ad")
    ad_name: str = Field(description="Name of the ad")
    adset_id: str = Field(description="Identifier for the ad set")
    adset_name: str = Field(description="Name of the ad set")
    buying_type: str | None = Field(default=None, description="Type of buying (e.g., auction, fixed price)")
    campaign_id: str = Field(description="Identifier for the campaign")
    campaign_name: str = Field(description="Name of the campaign")
    clicks: int = Field(description="Total number of clicks")
    cost_per_action_type_link_click: float | None = Field(default=None, description="Cost per action type for link clicks")
    cost_per_action_type_onsite_conversion_post_save: float | None = Field(default=None, description="Cost per action type for onsite conversions post save")
    cost_per_action_type_page_engagement: float | None = Field(default=None, description="Cost per action type for page engagements")
    cost_per_action_type_post_engagement: float | None = Field(default=None, description="Cost per action type for post engagements")
    cost_per_action_type_video_view: float | None = Field(default=None, description="Cost per action type for video views")
    cost_per_inline_link_click: float | None = Field(default=None, description="Cost per inline link click")
    cost_per_inline_post_engagement: float | None = Field(default=None, description="Cost per inline post engagement")
    cost_per_outbound_click_outbound_click: float | None = Field(default=None, description="Cost per outbound click")
    cost_per_unique_action_type_link_click: float | None = Field(default=None, description="Cost per unique action type for link clicks")
    cost_per_unique_action_type_page_engagement: float | None = Field(default=None, description="Cost per unique action type for page engagements")
    cost_per_unique_action_type_post_engagement: float | None = Field(default=None, description="Cost per unique action type for post engagements")
    cost_per_unique_action_type_video_view: float | None = Field(default=None, description="Cost per unique action type for video views")
    cost_per_unique_click: float | None = Field(default=None, description="Cost per unique click")
    cost_per_unique_inline_link_click: float | None = Field(default=None, description="Cost per unique inline link click")
    cost_per_unique_outbound_click_outbound_click: float | None = Field(default=None, description="Cost per unique outbound click")
    cpc: float | None = Field(default=None, description="Cost per click")
    cpm: float | None = Field(default=None, description="Cost per thousand impressions")
    cpp: float | None = Field(default=None, description="Cost per page post engagement")
    ctr: float | None = Field(default=None, description="Click-through rate")
    date_start: dt.date = Field(description="Start date of the data")
    date_stop: dt.date = Field(description="End date of the data")
    estimated_ad_recallers: str | None = Field(default=None, description="Estimated number of ad recallers")
    frequency: float | None = Field(default=None, description="Average frequency of impressions")
    impression_device: str | None = Field(default=None, description="Device used for viewing the ad impression")
    impressions: int = Field(description="Total number of impressions")
    inline_link_click_ctr: float | None = Field(default=None, description="Click-through rate for inline link clicks")
    inline_link_clicks: int | None = Field(default=None, description="Number of inline link clicks")
    inline_post_engagement: int | None = Field(default=None, description="Number of inline post engagements")
    objective: str | None = Field(default=None, description="Objective of the campaign")
    optimization_goal: str | None = Field(default=None, description="Goal for optimization")
    outbound_clicks_ctr_outbound_click: float | None = Field(default=None, description="Outbound click-through rate")
    outbound_clicks_outbound_click: float | None = Field(default=None, description="Number of outbound clicks")
    platform_position: str | None = Field(default=None, description="Position of the ad on the platform")
    publisher_platform: str | None = Field(default=None, description="Platform where the ad was published")
    reach: int | None = Field(default=None, description="Total number of people who saw the ad")
    social_spend: float | None = Field(default=None, description="Spend on social")
    spend: float = Field(description="Total spend on the ad")
    unique_actions_comment: int | None = Field(default=None, description="Unique comment actions")
    unique_actions_link_click: int | None = Field(default=None, description="Unique link click actions")
    unique_actions_onsite_conversion_post_save: int | None = Field(default=None, description="Unique onsite conversion post save actions")
    unique_actions_page_engagement: int | None = Field(default=None, description="Unique page engagement actions")
    unique_actions_post: int | None = Field(default=None, description="Unique post actions")
    unique_actions_post_engagement: int | None = Field(default=None, description="Unique post engagement actions")
    unique_actions_video_view: int | None = Field(default=None, description="Unique video view actions")
    unique_clicks: int | None = Field(default=None, description="Number of unique clicks")
    unique_ctr: float | None = Field(default=None, description="Unique click-through rate")
    unique_inline_link_click_ctr: float | None = Field(default=None, description="Unique inline link click-through rate")
    unique_inline_link_clicks: int | None = Field(default=None, description="Number of unique inline link clicks")
    unique_link_clicks_ctr: float | None = Field(default=None, description="Unique link clicks click-through rate")
    unique_outbound_clicks_ctr_outbound_click: float | None = Field(default=None, description="Unique outbound click-through rate")
    unique_outbound_clicks_outbound_click: int | None = Field(default=None, description="Number of unique outbound clicks")
    website_ctr_link_click: float | None = Field(default=None, description="Website click-through rate for link clicks")
