import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class Ads(Schema):
    """The Facebook Ads report provides insights into the performance and effectiveness of Facebook advertising campaigns. It includes key metrics such as clicks, impressions, spend, and various engagement actions, along with dimensions like campaign, ad set, and objective."""

    account_currency: str | None = Field(default=None, description="The currency used for the account")
    account_id: str | None = Field(default=None, description="Identifier for the account")
    account_name: str | None = Field(default=None, description="Name of the account")
    action_values_offsite_conversion_fb_pixel_purchase: float | None = Field(default=None, description="Value of offsite conversions tracked through the Facebook pixel for purchases")
    actions_comment: int | None = Field(default=None, description="Number of comments on posts or ads")
    actions_landing_page_view: int | None = Field(default=None, description="Number of times people clicked on a link that led to the advertiser's chosen destination")
    actions_link_click: int | None = Field(default=None, description="Number of clicks on links within the ad")
    actions_offsite_conversion_fb_pixel_lead: int | None = Field(default=None, description="Number of offsite conversions tracked through the Facebook pixel for leads")
    actions_offsite_conversion_fb_pixel_purchase: int | None = Field(default=None, description="Number of offsite conversions tracked through the Facebook pixel for purchases")
    actions_onsite_conversion_post_save: int | None = Field(default=None, description="Number of onsite conversions tracked after a post is saved")
    actions_page_engagement: int | None = Field(default=None, description="Number of engagements with a Facebook Page")
    actions_post: int | None = Field(default=None, description="Number of actions taken on a post")
    actions_post_engagement: int | None = Field(default=None, description="Number of engagements with posts")
    actions_post_reaction: int | None = Field(default=None, description="Number of reactions on posts")
    actions_video_view: int | None = Field(default=None, description="Number of views on videos")
    ad_id: str | None = Field(default=None, description="Identifier for the ad")
    ad_name: str | None = Field(default=None, description="Name of the ad")
    adset_id: str | None = Field(default=None, description="Identifier for the ad set")
    adset_name: str | None = Field(default=None, description="Name of the ad set")
    buying_type: str | None = Field(default=None, description="Type of buying, such as auction or fixed price")
    campaign_id: str | None = Field(default=None, description="Identifier for the campaign")
    campaign_name: str | None = Field(default=None, description="Name of the campaign")
    clicks: int | None = Field(default=None, description="Total number of clicks on the ad")
    cost_per_action_type_link_click: float | None = Field(default=None, description="Cost per action type for link clicks")
    cost_per_action_type_onsite_conversion_post_save: float | None = Field(default=None, description="Cost per action type for onsite conversions after post save")
    cost_per_action_type_page_engagement: float | None = Field(default=None, description="Cost per action type for page engagements")
    cost_per_action_type_post_engagement: float | None = Field(default=None, description="Cost per action type for post engagements")
    cost_per_action_type_video_view: float | None = Field(default=None, description="Cost per action type for video views")
    cost_per_inline_link_click: float | None = Field(default=None, description="Cost per inline link click")
    cost_per_inline_post_engagement: float | None = Field(default=None, description="Cost per inline post engagement")
    cost_per_outbound_click_outbound_click: float | None = Field(default=None, description="Cost per outbound click")
    cost_per_unique_action_type_link_click: float | None = Field(default=None, description="Cost per unique action type for link clicks")
    cost_per_unique_action_type_page_engagement: float | None = Field(default=None, description="Cost per unique action type for page engagements")
    cost_per_unique_action_type_post_engagement: float | None = Field(default=None, description="Cost per unique action type for post engagements")
    cost_per_unique_action_type_video_view: float | None = Field(default=None, description="Cost per unique action type for video views")
    cost_per_unique_click: float | None = Field(default=None, description="Cost per unique click")
    cost_per_unique_inline_link_click: float | None = Field(default=None, description="Cost per unique inline link click")
    cost_per_unique_outbound_click_outbound_click: float | None = Field(default=None, description="Cost per unique outbound click")
    cpc: float | None = Field(default=None, description="Cost per click")
    cpm: float | None = Field(default=None, description="Cost per thousand impressions")
    cpp: float | None = Field(default=None, description="Cost per page post engagement")
    ctr: float | None = Field(default=None, description="Click-through rate")
    date_start: dt.date | None = Field(default=None, description="Start date of the data")
    date_stop: dt.date | None = Field(default=None, description="End date of the data")
    estimated_ad_recallers: str | None = Field(default=None, description="Estimated number of people who would remember seeing the ad if asked within two days")
    frequency: float | None = Field(default=None, description="Average number of times each person saw the ad")
    impression_device: str | None = Field(default=None, description="Device used for viewing the ad impression")
    impressions: int | None = Field(default=None, description="Total number of times the ad was shown")
    inline_link_click_ctr: float | None = Field(default=None, description="Click-through rate for inline link clicks")
    inline_link_clicks: int | None = Field(default=None, description="Number of inline link clicks")
    inline_post_engagement: int | None = Field(default=None, description="Number of engagements with inline posts")
    objective: str | None = Field(default=None, description="Objective of the campaign")
    optimization_goal: str | None = Field(default=None, description="Goal for optimization")
    outbound_clicks_ctr_outbound_click: float | None = Field(default=None, description="Click-through rate for outbound clicks")
    outbound_clicks_outbound_click: float | None = Field(default=None, description="Number of outbound clicks")
    platform_position: str | None = Field(default=None, description="Position of the ad on the platform")
    publisher_platform: str | None = Field(default=None, description="Platform where the ad was published")
    reach: int | None = Field(default=None, description="Total number of people who saw the ad")
    social_spend: float | None = Field(default=None, description="Spend specifically on social media")
    spend: float | None = Field(default=None, description="Total spend on the ad")
    unique_actions_comment: int | None = Field(default=None, description="Number of unique actions (comments) on posts or ads")
    unique_actions_link_click: int | None = Field(default=None, description="Number of unique actions (link clicks) on the ad")
    unique_actions_onsite_conversion_post_save: int | None = Field(default=None, description="Number of unique actions (onsite conversions post save)")
    unique_actions_page_engagement: int | None = Field(default=None, description="Number of unique actions (page engagements)")
    unique_actions_post: int | None = Field(default=None, description="Number of unique actions (post actions)")
    unique_actions_post_engagement: int | None = Field(default=None, description="Number of unique actions (post engagements)")
    unique_actions_video_view: int | None = Field(default=None, description="Number of unique actions (video views)")
    unique_clicks: int | None = Field(default=None, description="Number of unique clicks on the ad")
    unique_ctr: float | None = Field(default=None, description="Unique click-through rate")
    unique_inline_link_click_ctr: float | None = Field(default=None, description="Unique click-through rate for inline link clicks")
    unique_inline_link_clicks: int | None = Field(default=None, description="Number of unique inline link clicks")
    unique_link_clicks_ctr: float | None = Field(default=None, description="Unique click-through rate for link clicks")
    unique_outbound_clicks_ctr_outbound_click: float | None = Field(default=None, description="Unique click-through rate for outbound clicks")
    unique_outbound_clicks_outbound_click: int | None = Field(default=None, description="Number of unique outbound clicks")
    website_ctr_link_click: float | None = Field(default=None, description="Click-through rate for website link clicks")
