import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class AdsStats(Schema):
    """The Facebook Ads report provides insights into the performance and effectiveness of Facebook advertising campaigns. It includes key metrics such as clicks, impressions, spend, and various engagement actions, along with dimensions like campaign, ad set, and objective."""

    account_currency: str | None = Field(default=None, description="The currency used for the account")
    account_id: str | None = Field(default=None, description="Identifier for the account")
    account_name: str | None = Field(default=None, description="Name of the account")
    action_values_add_payment_info: float | None = Field(default=None, description="Action values for adding payment info")
    action_values_add_to_cart: float | None = Field(default=None, description="Action values for adding to cart")
    action_values_initiate_checkout: float | None = Field(default=None, description="Action values for initiating checkout")
    action_values_offsite_conversion_fb_pixel_add_payment_info: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Add Payment Info")
    action_values_offsite_conversion_fb_pixel_add_to_cart: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Add to Cart")
    action_values_offsite_conversion_fb_pixel_initiate_checkout: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Initiate Checkout")
    action_values_offsite_conversion_fb_pixel_purchase: float | None = Field(default=None, description="Value of offsite conversions tracked through the Facebook pixel for purchases")
    action_values_offsite_conversion_fb_pixel_view_content: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - View Content")
    action_values_omni_add_to_cart: float | None = Field(default=None, description="Action values for adding to cart (omni-channel)")
    action_values_omni_initiated_checkout: float | None = Field(default=None, description="Action values for initiating checkout (omni-channel)")
    action_values_omni_purchase: float | None = Field(default=None, description="Action values for purchase (omni-channel)")
    action_values_omni_view_content: float | None = Field(default=None, description="Action values for viewing content (omni-channel)")
    action_values_onsite_app_purchase: float | None = Field(default=None, description="Action values for onsite app purchase")
    action_values_onsite_conversion_purchase: float | None = Field(default=None, description="Action values for onsite conversion purchase")
    action_values_onsite_web_add_to_cart: float | None = Field(default=None, description="Action values for onsite web add to cart")
    action_values_onsite_web_app_add_to_cart: float | None = Field(default=None, description="Action values for onsite web app add to cart")
    action_values_onsite_web_app_purchase: float | None = Field(default=None, description="Action values for onsite web app purchase")
    action_values_onsite_web_app_view_content: float | None = Field(default=None, description="Action values for onsite web app view content")
    action_values_onsite_web_purchase: float | None = Field(default=None, description="Action values for onsite web purchase")
    action_values_onsite_web_view_content: float | None = Field(default=None, description="Action values for onsite web view content")
    action_values_purchase: float | None = Field(default=None, description="Action values for purchase")
    action_values_view_content: float | None = Field(default=None, description="Action values for viewing content")
    actions_add_payment_info: int | None = Field(default=None, description="Number of actions to add payment info")
    actions_add_to_cart: int | None = Field(default=None, description="Number of actions to add to cart")
    actions_comment: int | None = Field(default=None, description="Number of comments on posts or ads")
    actions_complete_registration: int | None = Field(default=None, description="Number of actions for completing registration")
    actions_initiate_checkout: int | None = Field(default=None, description="Number of actions for initiating checkout")
    actions_landing_page_view: int | None = Field(default=None, description="Number of times people clicked on a link that led to the advertiser's chosen destination")
    actions_like: int | None = Field(default=None, description="Number of actions for liking")
    actions_link_click: int | None = Field(default=None, description="Number of clicks on links within the ad")
    actions_offsite_conversion_fb_pixel_add_payment_info: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Add Payment Info")
    actions_offsite_conversion_fb_pixel_add_to_cart: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Add to Cart")
    actions_offsite_conversion_fb_pixel_complete_registration: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Complete Registration")
    actions_offsite_conversion_fb_pixel_initiate_checkout: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Initiate Checkout")
    actions_offsite_conversion_fb_pixel_lead: int | None = Field(default=None, description="Number of offsite conversions tracked through the Facebook pixel for leads")
    actions_offsite_conversion_fb_pixel_purchase: int | None = Field(default=None, description="Number of offsite conversions tracked through the Facebook pixel for purchases")
    actions_offsite_conversion_fb_pixel_search: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Search")
    actions_offsite_conversion_fb_pixel_view_content: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - View Content")
    actions_omni_add_to_cart: int | None = Field(default=None, description="Number of omni-channel actions for adding to cart")
    actions_omni_add_to_wishlist: int | None = Field(default=None, description="Number of omni-channel actions for adding to wishlist")
    actions_omni_complete_registration: int | None = Field(default=None, description="Number of omni-channel actions for completing registration")
    actions_omni_initiated_checkout: int | None = Field(default=None, description="Number of omni-channel actions for initiating checkout")
    actions_omni_purchase: int | None = Field(default=None, description="Number of omni-channel actions for purchase")
    actions_omni_search: int | None = Field(default=None, description="Number of omni-channel actions for search")
    actions_omni_view_content: int | None = Field(default=None, description="Number of omni-channel actions for viewing content")
    actions_onsite_app_add_to_cart: int | None = Field(default=None, description="Number of onsite app actions for adding to cart")
    actions_onsite_app_purchase: int | None = Field(default=None, description="Number of onsite app actions for purchase")
    actions_onsite_app_view_content: int | None = Field(default=None, description="Number of onsite app actions for viewing content")
    actions_onsite_conversion_add_to_cart: int | None = Field(default=None, description="Number of onsite conversion actions for adding to cart")
    actions_onsite_conversion_add_to_wishlist: int | None = Field(default=None, description="Number of onsite conversion actions for adding to wishlist")
    actions_onsite_conversion_initiate_checkout: int | None = Field(default=None, description="Number of onsite conversion actions for initiating checkout")
    actions_onsite_conversion_post_save: int | None = Field(default=None, description="Number of onsite conversions tracked after a post is saved")
    actions_onsite_conversion_purchase: int | None = Field(default=None, description="Number of onsite conversion actions for purchase")
    actions_onsite_conversion_view_content: int | None = Field(default=None, description="Number of onsite conversion actions for viewing content")
    actions_onsite_web_add_to_cart: int | None = Field(default=None, description="Number of onsite web actions for adding to cart")
    actions_onsite_web_app_add_to_cart: int | None = Field(default=None, description="Number of onsite web app actions for adding to cart")
    actions_onsite_web_app_purchase: int | None = Field(default=None, description="Number of onsite web app actions for purchase")
    actions_onsite_web_app_view_content: int | None = Field(default=None, description="Number of onsite web app actions for viewing content")
    actions_onsite_web_purchase: int | None = Field(default=None, description="Number of onsite web actions for purchase")
    actions_onsite_web_view_content: int | None = Field(default=None, description="Number of onsite web actions for viewing content")
    actions_page_engagement: int | None = Field(default=None, description="Number of engagements with a Facebook Page")
    actions_post: int | None = Field(default=None, description="Number of actions taken on a post")
    actions_post_engagement: int | None = Field(default=None, description="Number of engagements with posts")
    actions_post_reaction: int | None = Field(default=None, description="Number of reactions on posts")
    actions_purchase: int | None = Field(default=None, description="Number of purchase actions")
    actions_search: int | None = Field(default=None, description="Number of actions for search")
    actions_video_view: int | None = Field(default=None, description="Number of views on videos")
    actions_view_content: int | None = Field(default=None, description="Number of actions for viewing content")
    ad_id: str | None = Field(default=None, description="Identifier for the ad")
    ad_name: str | None = Field(default=None, description="Name of the ad")
    adset_id: str | None = Field(default=None, description="Identifier for the ad set")
    adset_name: str | None = Field(default=None, description="Name of the ad set")
    attribution_setting: str | None = Field(default=None, description="The attribution setting applied to the conversion metrics")
    buying_type: str | None = Field(default=None, description="Type of buying, such as auction or fixed price")
    campaign_id: str | None = Field(default=None, description="Identifier for the campaign")
    campaign_name: str | None = Field(default=None, description="Name of the campaign")
    clicks: int | None = Field(default=None, description="Total number of clicks on the ad")
    converted_product_quantity: float | None = Field(default=None, description="Number of products purchased as a result of the ad")
    cost_per_action_type_add_payment_info: float | None = Field(default=None, description="Cost per action type for adding payment info")
    cost_per_action_type_add_to_cart: float | None = Field(default=None, description="Cost per action type for adding to cart")
    cost_per_action_type_complete_registration: float | None = Field(default=None, description="Cost per action type for completing registration")
    cost_per_action_type_initiate_checkout: float | None = Field(default=None, description="Cost per action type for initiating checkout")
    cost_per_action_type_landing_page_view: float | None = Field(default=None, description="Cost per action type for landing page view")
    cost_per_action_type_like: float | None = Field(default=None, description="Cost per action type for liking")
    cost_per_action_type_link_click: float | None = Field(default=None, description="Cost per action type for link clicks")
    cost_per_action_type_omni_add_to_cart: float | None = Field(default=None, description="Cost per action type for omni-channel adding to cart")
    cost_per_action_type_omni_add_to_wishlist: float | None = Field(default=None, description="Cost per action type for omni-channel adding to wishlist")
    cost_per_action_type_omni_complete_registration: float | None = Field(default=None, description="Cost per action type for omni-channel completing registration")
    cost_per_action_type_omni_initiated_checkout: float | None = Field(default=None, description="Cost per action type for omni-channel initiating checkout")
    cost_per_action_type_omni_purchase: float | None = Field(default=None, description="Cost per action type for omni-channel purchase")
    cost_per_action_type_omni_search: float | None = Field(default=None, description="Cost per action type for omni-channel search")
    cost_per_action_type_omni_view_content: float | None = Field(default=None, description="Cost per action type for omni-channel viewing content")
    cost_per_action_type_onsite_app_add_to_cart: float | None = Field(default=None, description="Cost per action type for onsite app adding to cart")
    cost_per_action_type_onsite_app_purchase: float | None = Field(default=None, description="Cost per action type for onsite app purchase")
    cost_per_action_type_onsite_app_view_content: float | None = Field(default=None, description="Cost per action type for onsite app viewing content")
    cost_per_action_type_onsite_conversion_add_to_wishlist: float | None = Field(default=None, description="Cost per action type for onsite conversion adding to wishlist")
    cost_per_action_type_onsite_conversion_initiate_checkout: float | None = Field(default=None, description="Cost per action type for onsite conversion initiating checkout")
    cost_per_action_type_onsite_conversion_post_save: float | None = Field(default=None, description="Cost per action type for onsite conversions after post save")
    cost_per_action_type_onsite_web_add_to_cart: float | None = Field(default=None, description="Cost per action type for onsite web adding to cart")
    cost_per_action_type_onsite_web_app_add_to_cart: float | None = Field(default=None, description="Cost per action type for onsite web app adding to cart")
    cost_per_action_type_onsite_web_app_purchase: float | None = Field(default=None, description="Cost per action type for onsite web app purchase")
    cost_per_action_type_onsite_web_app_view_content: float | None = Field(default=None, description="Cost per action type for onsite web app viewing content")
    cost_per_action_type_onsite_web_purchase: float | None = Field(default=None, description="Cost per action type for onsite web purchase")
    cost_per_action_type_onsite_web_view_content: float | None = Field(default=None, description="Cost per action type for onsite web viewing content")
    cost_per_action_type_page_engagement: float | None = Field(default=None, description="Cost per action type for page engagements")
    cost_per_action_type_post_engagement: float | None = Field(default=None, description="Cost per action type for post engagements")
    cost_per_action_type_purchase: float | None = Field(default=None, description="Cost per action type for purchase")
    cost_per_action_type_search: float | None = Field(default=None, description="Cost per action type for search")
    cost_per_action_type_video_view: float | None = Field(default=None, description="Cost per action type for video views")
    cost_per_action_type_view_content: float | None = Field(default=None, description="Cost per action type for viewing content")
    cost_per_inline_link_click: float | None = Field(default=None, description="Cost per inline link click")
    cost_per_inline_post_engagement: float | None = Field(default=None, description="Cost per inline post engagement")
    cost_per_outbound_click_outbound_click: float | None = Field(default=None, description="Cost per outbound click")
    cost_per_unique_action_type_commerce_event: float | None = Field(default=None, description="Cost per unique action type for commerce event")
    cost_per_unique_action_type_like: float | None = Field(default=None, description="Cost per unique action type for liking")
    cost_per_unique_action_type_link_click: float | None = Field(default=None, description="Cost per unique action type for link clicks")
    cost_per_unique_action_type_omni_add_to_cart: float | None = Field(default=None, description="Cost per unique action type for omni-channel adding to cart")
    cost_per_unique_action_type_omni_add_to_wishlist: float | None = Field(default=None, description="Cost per unique action type for omni-channel adding to wishlist")
    cost_per_unique_action_type_omni_initiated_checkout: float | None = Field(default=None, description="Cost per unique action type for omni-channel initiating checkout")
    cost_per_unique_action_type_omni_purchase: float | None = Field(default=None, description="Cost per unique action type for omni-channel purchase")
    cost_per_unique_action_type_omni_view_content: float | None = Field(default=None, description="Cost per unique action type for omni-channel viewing content")
    cost_per_unique_action_type_onsite_app_add_to_cart: float | None = Field(default=None, description="Cost per unique action type for onsite app adding to cart")
    cost_per_unique_action_type_onsite_app_purchase: float | None = Field(default=None, description="Cost per unique action type for onsite app purchase")
    cost_per_unique_action_type_onsite_app_view_content: float | None = Field(default=None, description="Cost per unique action type for onsite app viewing content")
    cost_per_unique_action_type_onsite_conversion_add_to_wishlist: float | None = Field(default=None, description="Cost per unique action type for onsite conversion adding to wishlist")
    cost_per_unique_action_type_onsite_conversion_initiate_checkout: float | None = Field(default=None, description="Cost per unique action type for onsite conversion initiating checkout")
    cost_per_unique_action_type_onsite_web_add_to_cart: float | None = Field(default=None, description="Cost per unique action type for onsite web adding to cart")
    cost_per_unique_action_type_onsite_web_app_add_to_cart: float | None = Field(default=None, description="Cost per unique action type for onsite web app adding to cart")
    cost_per_unique_action_type_onsite_web_app_purchase: float | None = Field(default=None, description="Cost per unique action type for onsite web app purchase")
    cost_per_unique_action_type_onsite_web_app_view_content: float | None = Field(default=None, description="Cost per unique action type for onsite web app viewing content")
    cost_per_unique_action_type_onsite_web_purchase: float | None = Field(default=None, description="Cost per unique action type for onsite web purchase")
    cost_per_unique_action_type_onsite_web_view_content: float | None = Field(default=None, description="Cost per unique action type for onsite web viewing content")
    cost_per_unique_action_type_page_engagement: float | None = Field(default=None, description="Cost per unique action type for page engagements")
    cost_per_unique_action_type_post_engagement: float | None = Field(default=None, description="Cost per unique action type for post engagements")
    cost_per_unique_action_type_video_view: float | None = Field(default=None, description="Cost per unique action type for video views")
    cost_per_unique_click: float | None = Field(default=None, description="Cost per unique click")
    cost_per_unique_inline_link_click: float | None = Field(default=None, description="Cost per unique inline link click")
    cost_per_unique_outbound_click_outbound_click: float | None = Field(default=None, description="Cost per unique outbound click")
    cpc: float | None = Field(default=None, description="Cost per click")
    cpm: float | None = Field(default=None, description="Cost per thousand impressions")
    cpp: float | None = Field(default=None, description="Cost per page post engagement")
    ctr: float | None = Field(default=None, description="Click-through rate")
    date_start: dt.date | None = Field(default=None, description="Start date of the data")
    date_stop: dt.date | None = Field(default=None, description="End date of the data")
    estimated_ad_recallers: str | None = Field(default=None, description="Estimated number of people who would remember seeing the ad if asked within two days")
    frequency: float | None = Field(default=None, description="Average number of times each person saw the ad")
    impression_device: str | None = Field(default=None, description="Device used for viewing the ad impression")
    impressions: int | None = Field(default=None, description="Total number of times the ad was shown")
    inline_link_click_ctr: float | None = Field(default=None, description="Click-through rate for inline link clicks")
    inline_link_clicks: int | None = Field(default=None, description="Number of inline link clicks")
    inline_post_engagement: int | None = Field(default=None, description="Number of engagements with inline posts")
    objective: str | None = Field(default=None, description="Objective of the campaign")
    optimization_goal: str | None = Field(default=None, description="Goal for optimization")
    outbound_clicks_ctr_outbound_click: float | None = Field(default=None, description="Click-through rate for outbound clicks")
    outbound_clicks_outbound_click: float | None = Field(default=None, description="Number of outbound clicks")
    platform_position: str | None = Field(default=None, description="Position of the ad on the platform")
    publisher_platform: str | None = Field(default=None, description="Platform where the ad was published")
    quality_ranking: str | None = Field(default=None, description="Ranking of the ad's perceived quality against ads competing for the same audience")
    reach: int | None = Field(default=None, description="Total number of people who saw the ad")
    social_spend: float | None = Field(default=None, description="Spend specifically on social media")
    spend: float | None = Field(default=None, description="Total spend on the ad")
    unique_actions_comment: int | None = Field(default=None, description="Number of unique actions (comments) on posts or ads")
    unique_actions_commerce_event: int | None = Field(default=None, description="Unique actions for commerce event")
    unique_actions_like: int | None = Field(default=None, description="Unique actions for liking")
    unique_actions_link_click: int | None = Field(default=None, description="Number of unique actions (link clicks) on the ad")
    unique_actions_omni_add_to_cart: int | None = Field(default=None, description="Unique actions for omni-channel adding to cart")
    unique_actions_omni_add_to_wishlist: int | None = Field(default=None, description="Unique actions for omni-channel adding to wishlist")
    unique_actions_omni_initiated_checkout: int | None = Field(default=None, description="Unique actions for omni-channel initiating checkout")
    unique_actions_omni_purchase: int | None = Field(default=None, description="Unique actions for omni-channel purchase")
    unique_actions_omni_view_content: int | None = Field(default=None, description="Unique actions for omni-channel viewing content")
    unique_actions_onsite_app_add_to_cart: int | None = Field(default=None, description="Unique actions for onsite app adding to cart")
    unique_actions_onsite_app_purchase: int | None = Field(default=None, description="Unique actions for onsite app purchase")
    unique_actions_onsite_app_view_content: int | None = Field(default=None, description="Unique actions for onsite app viewing content")
    unique_actions_onsite_conversion_add_to_cart: int | None = Field(default=None, description="Unique actions for onsite conversion adding to cart")
    unique_actions_onsite_conversion_add_to_wishlist: int | None = Field(default=None, description="Unique actions for onsite conversion adding to wishlist")
    unique_actions_onsite_conversion_initiate_checkout: int | None = Field(default=None, description="Unique actions for onsite conversion initiating checkout")
    unique_actions_onsite_conversion_post_save: int | None = Field(default=None, description="Number of unique actions (onsite conversions post save)")
    unique_actions_onsite_conversion_purchase: int | None = Field(default=None, description="Unique actions for onsite conversion purchase")
    unique_actions_onsite_conversion_view_content: int | None = Field(default=None, description="Unique actions for onsite conversion viewing content")
    unique_actions_onsite_web_add_to_cart: int | None = Field(default=None, description="Unique actions for onsite web adding to cart")
    unique_actions_onsite_web_app_add_to_cart: int | None = Field(default=None, description="Unique actions for onsite web app adding to cart")
    unique_actions_onsite_web_app_purchase: int | None = Field(default=None, description="Unique actions for onsite web app purchase")
    unique_actions_onsite_web_app_view_content: int | None = Field(default=None, description="Unique actions for onsite web app viewing content")
    unique_actions_onsite_web_purchase: int | None = Field(default=None, description="Unique actions for onsite web purchase")
    unique_actions_onsite_web_view_content: int | None = Field(default=None, description="Unique actions for onsite web viewing content")
    unique_actions_page_engagement: int | None = Field(default=None, description="Number of unique actions (page engagements)")
    unique_actions_post: int | None = Field(default=None, description="Number of unique actions (post actions)")
    unique_actions_post_engagement: int | None = Field(default=None, description="Number of unique actions (post engagements)")
    unique_actions_video_view: int | None = Field(default=None, description="Number of unique actions (video views)")
    unique_clicks: int | None = Field(default=None, description="Number of unique clicks on the ad")
    unique_ctr: float | None = Field(default=None, description="Unique click-through rate")
    unique_inline_link_click_ctr: float | None = Field(default=None, description="Unique click-through rate for inline link clicks")
    unique_inline_link_clicks: int | None = Field(default=None, description="Number of unique inline link clicks")
    unique_link_clicks_ctr: float | None = Field(default=None, description="Unique click-through rate for link clicks")
    unique_outbound_clicks_ctr_outbound_click: float | None = Field(default=None, description="Unique click-through rate for outbound clicks")
    unique_outbound_clicks_outbound_click: int | None = Field(default=None, description="Number of unique outbound clicks")
    website_ctr_link_click: float | None = Field(default=None, description="Click-through rate for website link clicks")
