import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class Campaigns(Schema):
    """The Campaigns report provides insights into the performance of your advertising campaigns. It includes key metrics such as clicks, impressions, spend, and engagement rates. With this information, advertisers can evaluate the effectiveness of their campaigns, identify successful strategies, and optimize their advertising efforts to achieve their objectives more efficiently."""

    account_currency: str | None = Field(default=None, description="The currency used for the account")
    account_id: int | None = Field(default=None, description="The ID of the account")
    account_name: str | None = Field(default=None, description="The name of the account")
    action_values_add_payment_info: float | None = Field(default=None, description="Action values for adding payment info")
    action_values_add_to_cart: float | None = Field(default=None, description="Action values for adding to cart")
    action_values_initiate_checkout: float | None = Field(default=None, description="Action values for initiating checkout")
    action_values_offsite_conversion_fb_pixel_add_payment_info: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Add Payment Info")
    action_values_offsite_conversion_fb_pixel_add_to_cart: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Add to Cart")
    action_values_offsite_conversion_fb_pixel_initiate_checkout: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Initiate Checkout")
    action_values_offsite_conversion_fb_pixel_purchase: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Purchase")
    action_values_offsite_conversion_fb_pixel_view_content: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - View Content")
    action_values_omni_add_to_cart: float | None = Field(default=None, description="Action values for adding to cart (omni-channel)")
    action_values_omni_initiated_checkout: float | None = Field(default=None, description="Action values for initiating checkout (omni-channel)")
    action_values_omni_purchase: float | None = Field(default=None, description="Action values for purchase (omni-channel)")
    action_values_omni_view_content: float | None = Field(default=None, description="Action values for viewing content (omni-channel)")
    action_values_onsite_app_purchase: float | None = Field(default=None, description="Action values for onsite app purchase")
    action_values_onsite_conversion_purchase: float | None = Field(default=None, description="Action values for onsite conversion purchase")
    action_values_onsite_web_add_to_cart: float | None = Field(default=None, description="Action values for onsite web add to cart")
    action_values_onsite_web_app_add_to_cart: float | None = Field(default=None, description="Action values for onsite web app add to cart")
    action_values_onsite_web_app_purchase: float | None = Field(default=None, description="Action values for onsite web app purchase")
    action_values_onsite_web_app_view_content: float | None = Field(default=None, description="Action values for onsite web app view content")
    action_values_onsite_web_purchase: float | None = Field(default=None, description="Action values for onsite web purchase")
    action_values_onsite_web_view_content: float | None = Field(default=None, description="Action values for onsite web view content")
    action_values_purchase: float | None = Field(default=None, description="Action values for purchase")
    action_values_view_content: float | None = Field(default=None, description="Action values for viewing content")
    actions_add_payment_info: int | None = Field(default=None, description="Number of actions to add payment info")
    actions_add_to_cart: int | None = Field(default=None, description="Number of actions to add to cart")
    actions_comment: int | None = Field(default=None, description="Number of actions for commenting")
    actions_complete_registration: int | None = Field(default=None, description="Number of actions for completing registration")
    actions_initiate_checkout: int | None = Field(default=None, description="Number of actions for initiating checkout")
    actions_landing_page_view: int | None = Field(default=None, description="Number of actions for landing page view")
    actions_like: int | None = Field(default=None, description="Number of actions for liking")
    actions_link_click: int | None = Field(default=None, description="Number of actions for link clicks")
    actions_offsite_conversion_fb_pixel_add_payment_info: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Add Payment Info")
    actions_offsite_conversion_fb_pixel_add_to_cart: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Add to Cart")
    actions_offsite_conversion_fb_pixel_complete_registration: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Complete Registration")
    actions_offsite_conversion_fb_pixel_initiate_checkout: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Initiate Checkout")
    actions_offsite_conversion_fb_pixel_purchase: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Purchase")
    actions_offsite_conversion_fb_pixel_search: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - Search")
    actions_offsite_conversion_fb_pixel_view_content: int | None = Field(default=None, description="Number of offsite conversion actions (Facebook Pixel) - View Content")
    actions_omni_add_to_cart: int | None = Field(default=None, description="Number of omni-channel actions for adding to cart")
    actions_omni_add_to_wishlist: int | None = Field(default=None, description="Number of omni-channel actions for adding to wishlist")
    actions_omni_complete_registration: int | None = Field(default=None, description="Number of omni-channel actions for completing registration")
    actions_omni_initiated_checkout: int | None = Field(default=None, description="Number of omni-channel actions for initiating checkout")
    actions_omni_purchase: int | None = Field(default=None, description="Number of omni-channel actions for purchase")
    actions_omni_search: int | None = Field(default=None, description="Number of omni-channel actions for search")
    actions_omni_view_content: int | None = Field(default=None, description="Number of omni-channel actions for viewing content")
    actions_onsite_app_add_to_cart: int | None = Field(default=None, description="Number of onsite app actions for adding to cart")
    actions_onsite_app_purchase: int | None = Field(default=None, description="Number of onsite app actions for purchase")
    actions_onsite_app_view_content: int | None = Field(default=None, description="Number of onsite app actions for viewing content")
    actions_onsite_conversion_add_to_cart: int | None = Field(default=None, description="Number of onsite conversion actions for adding to cart")
    actions_onsite_conversion_add_to_wishlist: int | None = Field(default=None, description="Number of onsite conversion actions for adding to wishlist")
    actions_onsite_conversion_initiate_checkout: int | None = Field(default=None, description="Number of onsite conversion actions for initiating checkout")
    actions_onsite_conversion_post_save: int | None = Field(default=None, description="Number of onsite conversion actions for post-save")
    actions_onsite_conversion_purchase: int | None = Field(default=None, description="Number of onsite conversion actions for purchase")
    actions_onsite_conversion_view_content: int | None = Field(default=None, description="Number of onsite conversion actions for viewing content")
    actions_onsite_web_add_to_cart: int | None = Field(default=None, description="Number of onsite web actions for adding to cart")
    actions_onsite_web_app_add_to_cart: int | None = Field(default=None, description="Number of onsite web app actions for adding to cart")
    actions_onsite_web_app_purchase: int | None = Field(default=None, description="Number of onsite web app actions for purchase")
    actions_onsite_web_app_view_content: int | None = Field(default=None, description="Number of onsite web app actions for viewing content")
    actions_onsite_web_purchase: int | None = Field(default=None, description="Number of onsite web actions for purchase")
    actions_onsite_web_view_content: int | None = Field(default=None, description="Number of onsite web actions for viewing content")
    actions_page_engagement: int | None = Field(default=None, description="Number of actions for page engagement")
    actions_post: int | None = Field(default=None, description="Number of actions for posts")
    actions_post_engagement: int | None = Field(default=None, description="Number of actions for post engagement")
    actions_post_reaction: int | None = Field(default=None, description="Number of actions for post reactions")
    actions_purchase: int | None = Field(default=None, description="Number of purchase actions")
    actions_search: int | None = Field(default=None, description="Number of actions for search")
    actions_video_view: int | None = Field(default=None, description="Number of actions for video views")
    actions_view_content: int | None = Field(default=None, description="Number of actions for viewing content")
    buying_type: str | None = Field(default=None, description="The type of buying")
    campaign_id: int | None = Field(default=None, description="The ID of the campaign")
    campaign_name: str | None = Field(default=None, description="The name of the campaign")
    clicks: int | None = Field(default=None, description="The number of clicks")
    cost_per_action_type_add_payment_info: float | None = Field(default=None, description="Cost per action type for adding payment info")
    cost_per_action_type_add_to_cart: float | None = Field(default=None, description="Cost per action type for adding to cart")
    cost_per_action_type_complete_registration: float | None = Field(default=None, description="Cost per action type for completing registration")
    cost_per_action_type_initiate_checkout: float | None = Field(default=None, description="Cost per action type for initiating checkout")
    cost_per_action_type_landing_page_view: float | None = Field(default=None, description="Cost per action type for landing page view")
    cost_per_action_type_like: float | None = Field(default=None, description="Cost per action type for liking")
    cost_per_action_type_link_click: float | None = Field(default=None, description="Cost per action type for link clicks")
    cost_per_action_type_omni_add_to_cart: float | None = Field(default=None, description="Cost per action type for omni-channel adding to cart")
    cost_per_action_type_omni_add_to_wishlist: float | None = Field(default=None, description="Cost per action type for omni-channel adding to wishlist")
    cost_per_action_type_omni_complete_registration: float | None = Field(default=None, description="Cost per action type for omni-channel completing registration")
    cost_per_action_type_omni_initiated_checkout: float | None = Field(default=None, description="Cost per action type for omni-channel initiating checkout")
    cost_per_action_type_omni_purchase: float | None = Field(default=None, description="Cost per action type for omni-channel purchase")
    cost_per_action_type_omni_search: float | None = Field(default=None, description="Cost per action type for omni-channel search")
    cost_per_action_type_omni_view_content: float | None = Field(default=None, description="Cost per action type for omni-channel viewing content")
    cost_per_action_type_onsite_app_add_to_cart: float | None = Field(default=None, description="Cost per action type for onsite app adding to cart")
    cost_per_action_type_onsite_app_purchase: float | None = Field(default=None, description="Cost per action type for onsite app purchase")
    cost_per_action_type_onsite_app_view_content: float | None = Field(default=None, description="Cost per action type for onsite app viewing content")
    cost_per_action_type_onsite_conversion_add_to_wishlist: float | None = Field(default=None, description="Cost per action type for onsite conversion adding to wishlist")
    cost_per_action_type_onsite_conversion_initiate_checkout: float | None = Field(default=None, description="Cost per action type for onsite conversion initiating checkout")
    cost_per_action_type_onsite_conversion_post_save: float | None = Field(default=None, description="Cost per action type for onsite conversion post-save")
    cost_per_action_type_onsite_web_add_to_cart: float | None = Field(default=None, description="Cost per action type for onsite web adding to cart")
    cost_per_action_type_onsite_web_app_add_to_cart: float | None = Field(default=None, description="Cost per action type for onsite web app adding to cart")
    cost_per_action_type_onsite_web_app_purchase: float | None = Field(default=None, description="Cost per action type for onsite web app purchase")
    cost_per_action_type_onsite_web_app_view_content: float | None = Field(default=None, description="Cost per action type for onsite web app viewing content")
    cost_per_action_type_onsite_web_purchase: float | None = Field(default=None, description="Cost per action type for onsite web purchase")
    cost_per_action_type_onsite_web_view_content: float | None = Field(default=None, description="Cost per action type for onsite web viewing content")
    cost_per_action_type_page_engagement: float | None = Field(default=None, description="Cost per action type for page engagement")
    cost_per_action_type_post_engagement: float | None = Field(default=None, description="Cost per action type for post engagement")
    cost_per_action_type_purchase: float | None = Field(default=None, description="Cost per action type for purchase")
    cost_per_action_type_search: float | None = Field(default=None, description="Cost per action type for search")
    cost_per_action_type_video_view: float | None = Field(default=None, description="Cost per action type for video view")
    cost_per_action_type_view_content: float | None = Field(default=None, description="Cost per action type for viewing content")
    cost_per_inline_link_click: float | None = Field(default=None, description="Cost per inline link click")
    cost_per_inline_post_engagement: float | None = Field(default=None, description="Cost per inline post engagement")
    cost_per_outbound_click_outbound_click: float | None = Field(default=None, description="Cost per outbound click")
    cost_per_unique_action_type_commerce_event: float | None = Field(default=None, description="Cost per unique action type for commerce event")
    cost_per_unique_action_type_like: float | None = Field(default=None, description="Cost per unique action type for liking")
    cost_per_unique_action_type_link_click: float | None = Field(default=None, description="Cost per unique action type for link clicks")
    cost_per_unique_action_type_omni_add_to_cart: float | None = Field(default=None, description="Cost per unique action type for omni-channel adding to cart")
    cost_per_unique_action_type_omni_add_to_wishlist: float | None = Field(default=None, description="Cost per unique action type for omni-channel adding to wishlist")
    cost_per_unique_action_type_omni_initiated_checkout: float | None = Field(default=None, description="Cost per unique action type for omni-channel initiating checkout")
    cost_per_unique_action_type_omni_purchase: float | None = Field(default=None, description="Cost per unique action type for omni-channel purchase")
    cost_per_unique_action_type_omni_view_content: float | None = Field(default=None, description="Cost per unique action type for omni-channel viewing content")
    cost_per_unique_action_type_onsite_app_add_to_cart: float | None = Field(default=None, description="Cost per unique action type for onsite app adding to cart")
    cost_per_unique_action_type_onsite_app_purchase: float | None = Field(default=None, description="Cost per unique action type for onsite app purchase")
    cost_per_unique_action_type_onsite_app_view_content: float | None = Field(default=None, description="Cost per unique action type for onsite app viewing content")
    cost_per_unique_action_type_onsite_conversion_add_to_wishlist: float | None = Field(default=None, description="Cost per unique action type for onsite conversion adding to wishlist")
    cost_per_unique_action_type_onsite_conversion_initiate_checkout: float | None = Field(default=None, description="Cost per unique action type for onsite conversion initiating checkout")
    cost_per_unique_action_type_onsite_web_add_to_cart: float | None = Field(default=None, description="Cost per unique action type for onsite web adding to cart")
    cost_per_unique_action_type_onsite_web_app_add_to_cart: float | None = Field(default=None, description="Cost per unique action type for onsite web app adding to cart")
    cost_per_unique_action_type_onsite_web_app_purchase: float | None = Field(default=None, description="Cost per unique action type for onsite web app purchase")
    cost_per_unique_action_type_onsite_web_app_view_content: float | None = Field(default=None, description="Cost per unique action type for onsite web app viewing content")
    cost_per_unique_action_type_onsite_web_purchase: float | None = Field(default=None, description="Cost per unique action type for onsite web purchase")
    cost_per_unique_action_type_onsite_web_view_content: float | None = Field(default=None, description="Cost per unique action type for onsite web viewing content")
    cost_per_unique_action_type_page_engagement: float | None = Field(default=None, description="Cost per unique action type for page engagement")
    cost_per_unique_action_type_post_engagement: float | None = Field(default=None, description="Cost per unique action type for post engagement")
    cost_per_unique_action_type_video_view: float | None = Field(default=None, description="Cost per unique action type for video view")
    cost_per_unique_click: float | None = Field(default=None, description="Cost per unique click")
    cost_per_unique_inline_link_click: float | None = Field(default=None, description="Cost per unique inline link click")
    cost_per_unique_outbound_click_outbound_click: float | None = Field(default=None, description="Cost per unique outbound click")
    cpc: float | None = Field(default=None, description="Cost per click")
    cpm: float | None = Field(default=None, description="Cost per thousand impressions")
    cpp: float | None = Field(default=None, description="Cost per purchase")
    ctr: float | None = Field(default=None, description="Click-through rate")
    date_start: dt.date | None = Field(default=None, description="The start date of the campaign")
    date_stop: dt.date | None = Field(default=None, description="The stop date of the campaign")
    estimated_ad_recallers: int | None = Field(default=None, description="The estimated number of ad recallers")
    frequency: float | None = Field(default=None, description="The frequency of the campaign")
    impression_device: str | None = Field(default=None, description="The device where the ad was displayed")
    impressions: int | None = Field(default=None, description="The number of impressions")
    inline_link_click_ctr: float | None = Field(default=None, description="Inline link click through rate")
    inline_link_clicks: int | None = Field(default=None, description="Inline link clicks")
    inline_post_engagement: int | None = Field(default=None, description="Inline post engagement")
    instant_experience_clicks_to_open: int | None = Field(default=None, description="The number of clicks to open instant experience")
    instant_experience_clicks_to_start: int | None = Field(default=None, description="The number of clicks to start instant experience")
    objective: str | None = Field(default=None, description="The objective of the campaign")
    optimization_goal: str | None = Field(default=None, description="The optimization goal of the campaign")
    outbound_clicks_ctr_outbound_click: float | None = Field(default=None, description="Outbound click through rate")
    outbound_clicks_outbound_click: int | None = Field(default=None, description="Outbound clicks")
    platform_position: str | None = Field(default=None, description="The position of the ad on the platform")
    publisher_platform: str | None = Field(default=None, description="The platform where the ad was published")
    reach: int | None = Field(default=None, description="The reach of the campaign")
    spend: float | None = Field(default=None, description="The amount spent on the campaign")
    unique_actions_comment: int | None = Field(default=None, description="Unique actions for commenting")
    unique_actions_commerce_event: int | None = Field(default=None, description="Unique actions for commerce event")
    unique_actions_like: int | None = Field(default=None, description="Unique actions for liking")
    unique_actions_link_click: int | None = Field(default=None, description="Unique actions for link clicking")
    unique_actions_omni_add_to_cart: int | None = Field(default=None, description="Unique actions for omni-channel adding to cart")
    unique_actions_omni_add_to_wishlist: int | None = Field(default=None, description="Unique actions for omni-channel adding to wishlist")
    unique_actions_omni_initiated_checkout: int | None = Field(default=None, description="Unique actions for omni-channel initiating checkout")
    unique_actions_omni_purchase: int | None = Field(default=None, description="Unique actions for omni-channel purchase")
    unique_actions_omni_view_content: int | None = Field(default=None, description="Unique actions for omni-channel viewing content")
    unique_actions_onsite_app_add_to_cart: int | None = Field(default=None, description="Unique actions for onsite app adding to cart")
    unique_actions_onsite_app_purchase: int | None = Field(default=None, description="Unique actions for onsite app purchase")
    unique_actions_onsite_app_view_content: int | None = Field(default=None, description="Unique actions for onsite app viewing content")
    unique_actions_onsite_conversion_add_to_cart: int | None = Field(default=None, description="Unique actions for onsite conversion adding to cart")
    unique_actions_onsite_conversion_add_to_wishlist: int | None = Field(default=None, description="Unique actions for onsite conversion adding to wishlist")
    unique_actions_onsite_conversion_initiate_checkout: int | None = Field(default=None, description="Unique actions for onsite conversion initiating checkout")
    unique_actions_onsite_conversion_post_save: int | None = Field(default=None, description="Unique actions for onsite conversion post save")
    unique_actions_onsite_conversion_purchase: int | None = Field(default=None, description="Unique actions for onsite conversion purchase")
    unique_actions_onsite_conversion_view_content: int | None = Field(default=None, description="Unique actions for onsite conversion viewing content")
    unique_actions_onsite_web_add_to_cart: int | None = Field(default=None, description="Unique actions for onsite web adding to cart")
    unique_actions_onsite_web_app_add_to_cart: int | None = Field(default=None, description="Unique actions for onsite web app adding to cart")
    unique_actions_onsite_web_app_purchase: int | None = Field(default=None, description="Unique actions for onsite web app purchase")
    unique_actions_onsite_web_app_view_content: int | None = Field(default=None, description="Unique actions for onsite web app viewing content")
    unique_actions_onsite_web_purchase: int | None = Field(default=None, description="Unique actions for onsite web purchase")
    unique_actions_onsite_web_view_content: int | None = Field(default=None, description="Unique actions for onsite web viewing content")
    unique_actions_page_engagement: int | None = Field(default=None, description="Unique actions for page engagement")
    unique_actions_post: int | None = Field(default=None, description="Unique actions for post")
    unique_actions_post_engagement: int | None = Field(default=None, description="Unique actions for post engagement")
    unique_actions_video_view: int | None = Field(default=None, description="Unique actions for video view")
    unique_clicks: int | None = Field(default=None, description="The number of unique clicks")
    unique_ctr: float | None = Field(default=None, description="Unique click-through rate")
    unique_inline_link_click_ctr: float | None = Field(default=None, description="Unique inline link click-through rate")
    unique_inline_link_clicks: int | None = Field(default=None, description="Unique inline link clicks")
    unique_link_clicks_ctr: float | None = Field(default=None, description="Unique link clicks click-through rate")
    unique_outbound_clicks_ctr_outbound_click: float | None = Field(default=None, description="Unique outbound clicks click-through rate")
    unique_outbound_clicks_outbound_click: int | None = Field(default=None, description="Unique outbound clicks")
    website_ctr_link_click: float | None = Field(default=None, description="Website click-through rate for link clicks")
