import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class CampaignsReport(Schema):
    """Facebook Ads campaign-level insights with metrics like clicks, impressions, spend, and engagement rates."""

    account_currency: str = Field(description="The currency used for the account")
    account_id: int = Field(description="The ID of the account")
    account_name: str = Field(description="The name of the account")
    action_values_add_payment_info: float | None = Field(default=None, description="Action values for adding payment info")
    action_values_add_to_cart: float | None = Field(default=None, description="Action values for adding to cart")
    action_values_initiate_checkout: float | None = Field(default=None, description="Action values for initiating checkout")
    action_values_offsite_conversion_fb_pixel_add_payment_info: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Add Payment Info")
    action_values_offsite_conversion_fb_pixel_add_to_cart: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Add to Cart")
    action_values_offsite_conversion_fb_pixel_initiate_checkout: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Initiate Checkout")
    action_values_offsite_conversion_fb_pixel_purchase: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - Purchase")
    action_values_offsite_conversion_fb_pixel_view_content: float | None = Field(default=None, description="Action values for offsite conversion (Facebook Pixel) - View Content")
    action_values_omni_add_to_cart: float | None = Field(default=None, description="Action values for adding to cart (omni-channel)")
    action_values_omni_initiated_checkout: float | None = Field(default=None, description="Action values for initiating checkout (omni-channel)")
    action_values_omni_purchase: float | None = Field(default=None, description="Action values for purchase (omni-channel)")
    action_values_omni_view_content: float | None = Field(default=None, description="Action values for viewing content (omni-channel)")
    action_values_onsite_app_purchase: float | None = Field(default=None, description="Action values for onsite app purchase")
    action_values_onsite_conversion_purchase: float | None = Field(default=None, description="Action values for onsite conversion purchase")
    action_values_onsite_web_add_to_cart: float | None = Field(default=None, description="Action values for onsite web add to cart")
    action_values_onsite_web_app_add_to_cart: float | None = Field(default=None, description="Action values for onsite web app add to cart")
    action_values_onsite_web_app_purchase: float | None = Field(default=None, description="Action values for onsite web app purchase")
    action_values_onsite_web_app_view_content: float | None = Field(default=None, description="Action values for onsite web app view content")
    action_values_onsite_web_purchase: float | None = Field(default=None, description="Action values for onsite web purchase")
    action_values_onsite_web_view_content: float | None = Field(default=None, description="Action values for onsite web view content")
    action_values_purchase: float | None = Field(default=None, description="Action values for purchase")
    action_values_view_content: float | None = Field(default=None, description="Action values for viewing content")
    actions_add_payment_info: int | None = Field(default=None, description="Number of actions to add payment info")
    actions_add_to_cart: int | None = Field(default=None, description="Number of actions to add to cart")
    actions_comment: int | None = Field(default=None, description="Number of comments")
    actions_complete_registration: int | None = Field(default=None, description="Number of completed registrations")
    actions_initiate_checkout: int | None = Field(default=None, description="Number of initiated checkouts")
    actions_landing_page_view: int | None = Field(default=None, description="Number of landing page views")
    actions_like: int | None = Field(default=None, description="Number of likes")
    actions_link_click: int | None = Field(default=None, description="Number of link clicks")
    actions_offsite_conversion_fb_pixel_add_payment_info: int | None = Field(default=None, description="Offsite conversion (Facebook Pixel) - Add Payment Info")
    actions_offsite_conversion_fb_pixel_add_to_cart: int | None = Field(default=None, description="Offsite conversion (Facebook Pixel) - Add to Cart")
    actions_offsite_conversion_fb_pixel_complete_registration: int | None = Field(default=None, description="Offsite conversion (Facebook Pixel) - Complete Registration")
    actions_offsite_conversion_fb_pixel_initiate_checkout: int | None = Field(default=None, description="Offsite conversion (Facebook Pixel) - Initiate Checkout")
    actions_offsite_conversion_fb_pixel_purchase: int | None = Field(default=None, description="Offsite conversion (Facebook Pixel) - Purchase")
    actions_offsite_conversion_fb_pixel_search: int | None = Field(default=None, description="Offsite conversion (Facebook Pixel) - Search")
    actions_offsite_conversion_fb_pixel_view_content: int | None = Field(default=None, description="Offsite conversion (Facebook Pixel) - View Content")
    actions_omni_add_to_cart: int | None = Field(default=None, description="Omni-channel add to cart actions")
    actions_omni_add_to_wishlist: int | None = Field(default=None, description="Omni-channel add to wishlist actions")
    actions_omni_complete_registration: int | None = Field(default=None, description="Omni-channel complete registration actions")
    actions_omni_initiated_checkout: int | None = Field(default=None, description="Omni-channel initiated checkout actions")
    actions_omni_purchase: int | None = Field(default=None, description="Omni-channel purchase actions")
    actions_omni_search: int | None = Field(default=None, description="Omni-channel search actions")
    actions_omni_view_content: int | None = Field(default=None, description="Omni-channel view content actions")
    actions_onsite_app_add_to_cart: int | None = Field(default=None, description="Onsite app add to cart actions")
    actions_onsite_app_purchase: int | None = Field(default=None, description="Onsite app purchase actions")
    actions_onsite_app_view_content: int | None = Field(default=None, description="Onsite app view content actions")
    actions_onsite_conversion_add_to_cart: int | None = Field(default=None, description="Onsite conversion add to cart actions")
    actions_onsite_conversion_add_to_wishlist: int | None = Field(default=None, description="Onsite conversion add to wishlist actions")
    actions_onsite_conversion_initiate_checkout: int | None = Field(default=None, description="Onsite conversion initiate checkout actions")
    actions_onsite_conversion_post_save: int | None = Field(default=None, description="Onsite conversion post save actions")
    actions_onsite_conversion_purchase: int | None = Field(default=None, description="Onsite conversion purchase actions")
    actions_onsite_conversion_view_content: int | None = Field(default=None, description="Onsite conversion view content actions")
    actions_onsite_web_add_to_cart: int | None = Field(default=None, description="Onsite web add to cart actions")
    actions_onsite_web_app_add_to_cart: int | None = Field(default=None, description="Onsite web app add to cart actions")
    actions_onsite_web_app_purchase: int | None = Field(default=None, description="Onsite web app purchase actions")
    actions_onsite_web_app_view_content: int | None = Field(default=None, description="Onsite web app view content actions")
    actions_onsite_web_purchase: int | None = Field(default=None, description="Onsite web purchase actions")
    actions_onsite_web_view_content: int | None = Field(default=None, description="Onsite web view content actions")
    actions_page_engagement: int | None = Field(default=None, description="Number of page engagement actions")
    actions_post: int | None = Field(default=None, description="Number of post actions")
    actions_post_engagement: int | None = Field(default=None, description="Number of post engagement actions")
    actions_post_reaction: int | None = Field(default=None, description="Number of post reactions")
    actions_purchase: int | None = Field(default=None, description="Number of purchase actions")
    actions_search: int | None = Field(default=None, description="Number of search actions")
    actions_video_view: int | None = Field(default=None, description="Number of video view actions")
    actions_view_content: int | None = Field(default=None, description="Number of view content actions")
    buying_type: str | None = Field(default=None, description="The type of buying")
    campaign_id: int = Field(description="The ID of the campaign")
    campaign_name: str = Field(description="The name of the campaign")
    clicks: int = Field(description="The number of clicks")
    cost_per_action_type_add_payment_info: float | None = Field(default=None, description="Cost per action type for adding payment info")
    cost_per_action_type_add_to_cart: float | None = Field(default=None, description="Cost per action type for adding to cart")
    cost_per_action_type_complete_registration: float | None = Field(default=None, description="Cost per action type for completing registration")
    cost_per_action_type_initiate_checkout: float | None = Field(default=None, description="Cost per action type for initiating checkout")
    cost_per_action_type_landing_page_view: float | None = Field(default=None, description="Cost per action type for landing page view")
    cost_per_action_type_like: float | None = Field(default=None, description="Cost per action type for liking")
    cost_per_action_type_link_click: float | None = Field(default=None, description="Cost per action type for link clicks")
    cost_per_action_type_omni_add_to_cart: float | None = Field(default=None, description="Cost per action type for omni-channel adding to cart")
    cost_per_action_type_omni_purchase: float | None = Field(default=None, description="Cost per action type for omni-channel purchase")
    cost_per_action_type_omni_view_content: float | None = Field(default=None, description="Cost per action type for omni-channel viewing content")
    cost_per_action_type_page_engagement: float | None = Field(default=None, description="Cost per action type for page engagement")
    cost_per_action_type_post_engagement: float | None = Field(default=None, description="Cost per action type for post engagement")
    cost_per_action_type_purchase: float | None = Field(default=None, description="Cost per action type for purchase")
    cost_per_action_type_video_view: float | None = Field(default=None, description="Cost per action type for video view")
    cost_per_action_type_view_content: float | None = Field(default=None, description="Cost per action type for viewing content")
    cost_per_inline_link_click: float | None = Field(default=None, description="Cost per inline link click")
    cost_per_inline_post_engagement: float | None = Field(default=None, description="Cost per inline post engagement")
    cost_per_outbound_click_outbound_click: float | None = Field(default=None, description="Cost per outbound click")
    cost_per_unique_action_type_link_click: float | None = Field(default=None, description="Cost per unique action type for link clicks")
    cost_per_unique_action_type_page_engagement: float | None = Field(default=None, description="Cost per unique action type for page engagement")
    cost_per_unique_action_type_post_engagement: float | None = Field(default=None, description="Cost per unique action type for post engagement")
    cost_per_unique_action_type_video_view: float | None = Field(default=None, description="Cost per unique action type for video view")
    cost_per_unique_click: float | None = Field(default=None, description="Cost per unique click")
    cost_per_unique_inline_link_click: float | None = Field(default=None, description="Cost per unique inline link click")
    cost_per_unique_outbound_click_outbound_click: float | None = Field(default=None, description="Cost per unique outbound click")
    cpc: float | None = Field(default=None, description="Cost per click")
    cpm: float | None = Field(default=None, description="Cost per thousand impressions")
    cpp: float | None = Field(default=None, description="Cost per purchase")
    ctr: float | None = Field(default=None, description="Click-through rate")
    date_start: dt.date = Field(description="The start date of the reporting period")
    date_stop: dt.date = Field(description="The stop date of the reporting period")
    estimated_ad_recallers: int | None = Field(default=None, description="Estimated number of ad recallers")
    frequency: float | None = Field(default=None, description="Average frequency of impressions")
    impression_device: str | None = Field(default=None, description="The device where the ad was displayed")
    impressions: int = Field(description="The number of impressions")
    inline_link_click_ctr: float | None = Field(default=None, description="Inline link click-through rate")
    inline_link_clicks: int | None = Field(default=None, description="Number of inline link clicks")
    inline_post_engagement: int | None = Field(default=None, description="Number of inline post engagements")
    instant_experience_clicks_to_open: int | None = Field(default=None, description="Clicks to open instant experience")
    instant_experience_clicks_to_start: int | None = Field(default=None, description="Clicks to start instant experience")
    objective: str | None = Field(default=None, description="The objective of the campaign")
    optimization_goal: str | None = Field(default=None, description="The optimization goal")
    outbound_clicks_ctr_outbound_click: float | None = Field(default=None, description="Outbound click-through rate")
    outbound_clicks_outbound_click: int | None = Field(default=None, description="Number of outbound clicks")
    platform_position: str | None = Field(default=None, description="Position of the ad on the platform")
    publisher_platform: str | None = Field(default=None, description="Platform where the ad was published")
    reach: int | None = Field(default=None, description="The reach of the campaign")
    social_spend: float | None = Field(default=None, description="Spend on social")
    spend: float = Field(description="The amount spent")
    unique_actions_comment: int | None = Field(default=None, description="Unique comment actions")
    unique_actions_commerce_event: int | None = Field(default=None, description="Unique commerce event actions")
    unique_actions_like: int | None = Field(default=None, description="Unique like actions")
    unique_actions_link_click: int | None = Field(default=None, description="Unique link click actions")
    unique_actions_page_engagement: int | None = Field(default=None, description="Unique page engagement actions")
    unique_actions_post: int | None = Field(default=None, description="Unique post actions")
    unique_actions_post_engagement: int | None = Field(default=None, description="Unique post engagement actions")
    unique_actions_video_view: int | None = Field(default=None, description="Unique video view actions")
    unique_clicks: int | None = Field(default=None, description="Number of unique clicks")
    unique_ctr: float | None = Field(default=None, description="Unique click-through rate")
    unique_inline_link_click_ctr: float | None = Field(default=None, description="Unique inline link click-through rate")
    unique_inline_link_clicks: int | None = Field(default=None, description="Number of unique inline link clicks")
    unique_link_clicks_ctr: float | None = Field(default=None, description="Unique link clicks click-through rate")
    unique_outbound_clicks_ctr_outbound_click: float | None = Field(default=None, description="Unique outbound click-through rate")
    unique_outbound_clicks_outbound_click: int | None = Field(default=None, description="Number of unique outbound clicks")
    website_ctr_link_click: float | None = Field(default=None, description="Website click-through rate for link clicks")
