import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class VideosStats(Schema):
    """The Videos report provides insights into video ad performance on Facebook. It includes key metrics such as video views, engagement actions (such as comments, likes, and shares), click-through rates, and viewer retention rates. Advertisers can leverage this data to evaluate the effectiveness of their video content, optimize targeting and creative strategies, and enhance overall campaign performance."""

    account_currency: str | None = Field(default=None, description="The currency used by the ad account (e.g., USD, EUR).")
    account_id: str | None = Field(default=None, description="The unique ID for the Meta ad account.")
    account_name: str | None = Field(default=None, description="The name of the Meta ad account.")
    action_values_add_to_cart: float | None = Field(default=None, description="Total value of 'Add to Cart' actions.")
    action_values_add_to_wishlist: float | None = Field(default=None, description="Total value of 'Add to Wishlist' actions.")
    action_values_offsite_conversion_fb_pixel_add_to_cart: float | None = Field(default=None, description="Value of Pixel-tracked 'Add to Cart' events.")
    action_values_offsite_conversion_fb_pixel_add_to_wishlist: float | None = Field(default=None, description="Value of Pixel-tracked 'Add to Wishlist' events.")
    action_values_offsite_conversion_fb_pixel_purchase: float | None = Field(default=None, description="Total conversion value of Pixel-tracked purchases.")
    action_values_offsite_conversion_fb_pixel_view_content: float | None = Field(default=None, description="Value of Pixel-tracked content views.")
    action_values_omni_add_to_cart: float | None = Field(default=None, description="Value of omnichannel 'Add to Cart' events.")
    action_values_omni_add_to_wishlist: float | None = Field(default=None, description="Value of omnichannel 'Add to Wishlist' events.")
    action_values_omni_purchase: float | None = Field(default=None, description="Value of omnichannel purchases.")
    action_values_omni_view_content: float | None = Field(default=None, description="Value of omnichannel content views.")
    action_values_onsite_web_add_to_cart: float | None = Field(default=None, description="Value of on-site web 'Add to Cart' events.")
    action_values_onsite_web_app_add_to_cart: float | None = Field(default=None, description="Value of web app 'Add to Cart' events.")
    action_values_onsite_web_app_purchase: float | None = Field(default=None, description="Value of web app purchases.")
    action_values_onsite_web_app_view_content: float | None = Field(default=None, description="Value of web app content views.")
    action_values_onsite_web_purchase: float | None = Field(default=None, description="Value of on-site web purchases.")
    action_values_onsite_web_view_content: float | None = Field(default=None, description="Value of on-site web content views.")
    action_values_purchase: float | None = Field(default=None, description="Total value of all purchases.")
    action_values_view_content: float | None = Field(default=None, description="Total value of content views.")
    action_values_web_app_in_store_purchase: float | None = Field(default=None, description="Value of in-store purchases from web app.")
    action_values_web_in_store_purchase: float | None = Field(default=None, description="Value of in-store purchases from web.")
    actions_add_to_cart: int | None = Field(default=None, description="Total number of 'Add to Cart' actions.")
    actions_add_to_wishlist: int | None = Field(default=None, description="Total number of 'Add to Wishlist' actions.")
    actions_comment: int | None = Field(default=None, description="The number of comments on the ad.")
    actions_landing_page_view: int | None = Field(default=None, description="The number of times a person clicked an ad and successfully loaded the destination URL.")
    actions_like: int | None = Field(default=None, description="The number of likes on the page or post.")
    actions_link_click: int | None = Field(default=None, description="The number of clicks on links within the ad.")
    actions_offsite_content_view_add_meta_leads: int | None = Field(default=None, description="Offsite content views and lead generation actions.")
    actions_offsite_conversion_fb_pixel_add_to_cart: int | None = Field(default=None, description="Pixel-tracked 'Add to Cart' events.")
    actions_offsite_conversion_fb_pixel_add_to_wishlist: int | None = Field(default=None, description="Pixel-tracked 'Add to Wishlist' events.")
    actions_offsite_conversion_fb_pixel_purchase: int | None = Field(default=None, description="Pixel-tracked 'Purchase' events.")
    actions_offsite_conversion_fb_pixel_view_content: int | None = Field(default=None, description="Pixel-tracked 'View Content' events.")
    actions_omni_add_to_cart: int | None = Field(default=None, description="Omnichannel 'Add to Cart' events.")
    actions_omni_add_to_wishlist: int | None = Field(default=None, description="Omnichannel 'Add to Wishlist' events.")
    actions_omni_landing_page_view: int | None = Field(default=None, description="Omnichannel landing page views.")
    actions_omni_purchase: int | None = Field(default=None, description="Omnichannel purchase events.")
    actions_omni_view_content: int | None = Field(default=None, description="Omnichannel content views.")
    actions_onsite_app_view_content: int | None = Field(default=None, description="App content views occurring within the Meta ecosystem.")
    actions_onsite_conversion_messaging_block: int | None = Field(default=None, description="Number of times messaging was blocked onsite.")
    actions_onsite_conversion_post_net_like: int | None = Field(default=None, description="Net likes on the post.")
    actions_onsite_conversion_post_net_save: int | None = Field(default=None, description="Net saves on the post.")
    actions_onsite_conversion_post_save: int | None = Field(default=None, description="Number of post saves.")
    actions_onsite_conversion_post_unlike: int | None = Field(default=None, description="Number of unlikes on the post.")
    actions_onsite_conversion_post_unsave: int | None = Field(default=None, description="Number of unsaves on the post.")
    actions_onsite_conversion_view_content: int | None = Field(default=None, description="Content views occurring on-site.")
    actions_onsite_web_add_to_cart: int | None = Field(default=None, description="Web-based 'Add to Cart' actions occurring on-site.")
    actions_onsite_web_app_add_to_cart: int | None = Field(default=None, description="Web app 'Add to Cart' actions.")
    actions_onsite_web_app_purchase: int | None = Field(default=None, description="Web app purchase actions.")
    actions_onsite_web_app_view_content: int | None = Field(default=None, description="Web app content view actions.")
    actions_onsite_web_purchase: int | None = Field(default=None, description="Web-based purchase actions occurring on-site.")
    actions_onsite_web_view_content: int | None = Field(default=None, description="Web-based content views occurring on-site.")
    actions_page_engagement: int | None = Field(default=None, description="The total number of actions people took on your Page and its posts.")
    actions_post: int | None = Field(default=None, description="The number of posts made.")
    actions_post_engagement: int | None = Field(default=None, description="The total number of actions that people take involving your ads.")
    actions_post_interaction_gross: int | None = Field(default=None, description="Gross number of interactions with the post.")
    actions_post_reaction: int | None = Field(default=None, description="Total reactions on the post (Like, Love, Haha, etc.).")
    actions_purchase: int | None = Field(default=None, description="Total number of purchase actions.")
    actions_video_view: int | None = Field(default=None, description="Total number of video views.")
    actions_view_content: int | None = Field(default=None, description="Total content view actions.")
    actions_web_app_in_store_purchase: int | None = Field(default=None, description="In-store purchases driven by web app.")
    actions_web_in_store_purchase: int | None = Field(default=None, description="In-store purchases driven by web.")
    ad_id: str | None = Field(default=None, description="The unique ID of the specific advertisement.")
    ad_name: str | None = Field(default=None, description="The name given to the specific advertisement.")
    adset_id: str | None = Field(default=None, description="The unique ID of the ad set.")
    adset_name: str | None = Field(default=None, description="The name of the ad set.")
    attribution_setting: str | None = Field(default=None, description="The window of time for attributing conversions to ads.")
    buying_type: str | None = Field(default=None, description="The method used to pay for and bid on ads (e.g., AUCTION).")
    campaign_id: str | None = Field(default=None, description="The unique ID of the ad campaign.")
    campaign_name: str | None = Field(default=None, description="The name of the ad campaign.")
    clicks: int | None = Field(default=None, description="The total number of clicks on the ad.")
    date_start: dt.date | None = Field(default=None, description="The start date for the reporting period.")
    date_stop: dt.date | None = Field(default=None, description="The end date for the reporting period.")
    impression_device: str | None = Field(default=None, description="The device used by the person seeing the ad (e.g., iphone, android_smartphone).")
    impressions: int | None = Field(default=None, description="The number of times the ad was on screen.")
    inline_post_engagement: int | None = Field(default=None, description="Engagements occurring directly on the ad post.")
    platform_position: str | None = Field(default=None, description="Where the ad was located on the platform (e.g., feed, stories).")
    publisher_platform: str | None = Field(default=None, description="The platform where the ad was shown (e.g., facebook, instagram).")
    reach: int | None = Field(default=None, description="The number of unique people who saw the ad at least once.")
    spend: float | None = Field(default=None, description="The total amount of money spent on the ad.")
    video_30_sec_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched for 30 seconds.")
    video_avg_time_watched_actions_video_view: float | None = Field(default=None, description="The average time people spent watching the video.")
    video_p_100_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched to 100% completion.")
    video_p_25_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched to at least 25%.")
    video_p_50_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched to at least 50%.")
    video_p_75_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched to at least 75%.")
    video_p_95_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched to at least 95%.")
    video_play_actions_video_view: int | None = Field(default=None, description="Number of times the video play event was triggered.")
    website_ctr_link_click: float | None = Field(default=None, description="Click-through rate for links to the website.")
