import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class VideosReport(Schema):
    """Facebook Ads video ad performance with view retention, engagement, and conversion metrics."""

    account_currency: str = Field(description="The currency used by the ad account")
    account_id: str = Field(description="The unique ID for the Meta ad account")
    account_name: str = Field(description="The name of the Meta ad account")
    action_values_add_to_cart: float | None = Field(default=None, description="Total value of Add to Cart actions")
    action_values_add_to_wishlist: float | None = Field(default=None, description="Total value of Add to Wishlist actions")
    action_values_offsite_conversion_fb_pixel_add_to_cart: float | None = Field(default=None, description="Value of Pixel-tracked Add to Cart events")
    action_values_offsite_conversion_fb_pixel_add_to_wishlist: float | None = Field(default=None, description="Value of Pixel-tracked Add to Wishlist events")
    action_values_offsite_conversion_fb_pixel_purchase: float | None = Field(default=None, description="Total conversion value of Pixel-tracked purchases")
    action_values_offsite_conversion_fb_pixel_view_content: float | None = Field(default=None, description="Value of Pixel-tracked content views")
    action_values_omni_add_to_cart: float | None = Field(default=None, description="Value of omnichannel Add to Cart events")
    action_values_omni_add_to_wishlist: float | None = Field(default=None, description="Value of omnichannel Add to Wishlist events")
    action_values_omni_purchase: float | None = Field(default=None, description="Value of omnichannel purchases")
    action_values_omni_view_content: float | None = Field(default=None, description="Value of omnichannel content views")
    action_values_onsite_web_add_to_cart: float | None = Field(default=None, description="Value of on-site web Add to Cart events")
    action_values_onsite_web_app_add_to_cart: float | None = Field(default=None, description="Value of web app Add to Cart events")
    action_values_onsite_web_app_purchase: float | None = Field(default=None, description="Value of web app purchases")
    action_values_onsite_web_app_view_content: float | None = Field(default=None, description="Value of web app content views")
    action_values_onsite_web_purchase: float | None = Field(default=None, description="Value of on-site web purchases")
    action_values_onsite_web_view_content: float | None = Field(default=None, description="Value of on-site web content views")
    action_values_purchase: float | None = Field(default=None, description="Total value of all purchases")
    action_values_view_content: float | None = Field(default=None, description="Total value of content views")
    actions_add_to_cart: int | None = Field(default=None, description="Total number of Add to Cart actions")
    actions_add_to_wishlist: int | None = Field(default=None, description="Total number of Add to Wishlist actions")
    actions_comment: int | None = Field(default=None, description="Number of comments on the ad")
    actions_landing_page_view: int | None = Field(default=None, description="Number of landing page views")
    actions_like: int | None = Field(default=None, description="Number of likes")
    actions_link_click: int | None = Field(default=None, description="Number of link clicks")
    actions_offsite_conversion_fb_pixel_add_to_cart: int | None = Field(default=None, description="Pixel-tracked Add to Cart events")
    actions_offsite_conversion_fb_pixel_add_to_wishlist: int | None = Field(default=None, description="Pixel-tracked Add to Wishlist events")
    actions_offsite_conversion_fb_pixel_purchase: int | None = Field(default=None, description="Pixel-tracked Purchase events")
    actions_offsite_conversion_fb_pixel_view_content: int | None = Field(default=None, description="Pixel-tracked View Content events")
    actions_omni_add_to_cart: int | None = Field(default=None, description="Omnichannel Add to Cart events")
    actions_omni_add_to_wishlist: int | None = Field(default=None, description="Omnichannel Add to Wishlist events")
    actions_omni_purchase: int | None = Field(default=None, description="Omnichannel purchase events")
    actions_omni_view_content: int | None = Field(default=None, description="Omnichannel content views")
    actions_onsite_web_add_to_cart: int | None = Field(default=None, description="Web-based Add to Cart actions")
    actions_onsite_web_app_add_to_cart: int | None = Field(default=None, description="Web app Add to Cart actions")
    actions_onsite_web_app_purchase: int | None = Field(default=None, description="Web app purchase actions")
    actions_onsite_web_app_view_content: int | None = Field(default=None, description="Web app content view actions")
    actions_onsite_web_purchase: int | None = Field(default=None, description="Web-based purchase actions")
    actions_onsite_web_view_content: int | None = Field(default=None, description="Web-based content view actions")
    actions_page_engagement: int | None = Field(default=None, description="Total page engagement actions")
    actions_post: int | None = Field(default=None, description="Number of posts")
    actions_post_engagement: int | None = Field(default=None, description="Total post engagement actions")
    actions_post_reaction: int | None = Field(default=None, description="Total reactions on the post")
    actions_purchase: int | None = Field(default=None, description="Total purchase actions")
    actions_video_view: int | None = Field(default=None, description="Total video views")
    actions_view_content: int | None = Field(default=None, description="Total content view actions")
    ad_id: str = Field(description="The unique ID of the advertisement")
    ad_name: str = Field(description="The name of the advertisement")
    adset_id: str = Field(description="The unique ID of the ad set")
    adset_name: str = Field(description="The name of the ad set")
    attribution_setting: str | None = Field(default=None, description="The attribution window for conversions")
    buying_type: str | None = Field(default=None, description="The method used to pay for and bid on ads")
    campaign_id: str = Field(description="The unique ID of the ad campaign")
    campaign_name: str = Field(description="The name of the ad campaign")
    clicks: int = Field(description="The total number of clicks")
    date_start: dt.date = Field(description="The start date for the reporting period")
    date_stop: dt.date = Field(description="The end date for the reporting period")
    impression_device: str | None = Field(default=None, description="The device used by the person seeing the ad")
    impressions: int = Field(description="The number of times the ad was on screen")
    inline_post_engagement: int | None = Field(default=None, description="Engagements on the ad post")
    platform_position: str | None = Field(default=None, description="Where the ad was located on the platform")
    publisher_platform: str | None = Field(default=None, description="The platform where the ad was shown")
    reach: int | None = Field(default=None, description="Number of unique people who saw the ad")
    spend: float = Field(description="The total amount spent on the ad")
    video_30_sec_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched for 30 seconds")
    video_avg_time_watched_actions_video_view: float | None = Field(default=None, description="Average time people spent watching the video")
    video_p_100_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched to 100%")
    video_p_25_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched to 25%")
    video_p_50_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched to 50%")
    video_p_75_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched to 75%")
    video_p_95_watched_actions_video_view: int | None = Field(default=None, description="Number of times the video was watched to 95%")
    video_play_actions_video_view: int | None = Field(default=None, description="Number of video play events")
    website_ctr_link_click: float | None = Field(default=None, description="Click-through rate for links to the website")
