import datetime as dt

from interloper.schema import Schema
from pydantic import Field


class AdsMetadata(Schema):
    """Tiktok Metadata for ads"""

    ad_format: str | None = Field(default=None, description="Format of the ad")
    ad_id: str | None = Field(default=None, description="Unique identifier for the ad")
    ad_name: str | None = Field(default=None, description="Name of the ad")
    ad_text: str | None = Field(default=None, description="Text content used in the ad")
    ad_texts: str | None = Field(default=None, description="List or alternative versions of text content used in the ad")
    advertiser_id: str | None = Field(default=None, description="Unique identifier for the advertiser")
    adgroup_id: str | None = Field(default=None, description="Unique identifier for the ad group")
    adgroup_name: str | None = Field(default=None, description="Name of the ad group the ad belongs to")
    aigc_disclosure_type: str | None = Field(default=None, description="Type of AIGC disclosure for the ad")
    app_name: str | None = Field(default=None, description="Name of the app being promoted")
    avatar_icon_web_uri: str | None = Field(default=None, description="URI for the web avatar icon used in the ad")
    brand_safety_postbid_partner: str | None = Field(default=None, description="Brand safety post-bid partner for the ad")
    brand_safety_vast_url: str | None = Field(default=None, description="VAST URL used for brand safety tracking verification")
    branded_content_disabled: str | None = Field(default=None, description="Indicates if branded content is disabled")
    call_to_action: str | None = Field(default=None, description="Call to action displayed on the ad")
    call_to_action_id: str | None = Field(default=None, description="Identifier for the call to action")
    campaign_automation_type: str | None = Field(default=None, description="Automation type applied to the ad campaign")
    campaign_id: str | None = Field(default=None, description="Unique identifier for the campaign")
    campaign_name: str | None = Field(default=None, description="Name of the campaign")
    card_id: str | None = Field(default=None, description="Unique identifier for the interactive card asset")
    carousel_image_labels: str | None = Field(default=None, description="Labels or captions assigned to the carousel images")
    click_tracking_url: str | None = Field(default=None, description="URL for click tracking")
    create_time: dt.datetime | None = Field(default=None, description="Timestamp when the ad was created")
    creative_authorized: bool | None = Field(default=None, description="Indicates if the ad creative is authorized")
    creative_type: str | None = Field(default=None, description="The specific layout or type format of the ad creative")
    dark_post_status: str | None = Field(default=None, description="Dark post status of the ad")
    deeplink: str | None = Field(default=None, description="Deeplink URL for the ad")
    deeplink_type: str | None = Field(default=None, description="Type of deeplink used in the ad")
    display_name: str | None = Field(default=None, description="Display name associated with the ad")
    fallback_type: str | None = Field(default=None, description="Type of fallback content used")
    identity_authorized_bc_id: str | None = Field(default=None, description="Authorized business center ID for the identity")
    identity_id: str | None = Field(default=None, description="Unique identifier for the ad's identity")
    identity_type: str | None = Field(default=None, description="Type of identity associated with the ad")
    image_ids: str | None = Field(default=None, description="Comma-separated list of image IDs used in the ad")
    impression_tracking_url: str | None = Field(default=None, description="URL for impression tracking")
    is_aco: bool | None = Field(default=None, description="Indicates if the ad uses ACO (Automated Creative Optimization)")
    is_new_structure: bool | None = Field(default=None, description="Indicates if the ad uses a new structure")
    item_duet_status: str | None = Field(default=None, description="Status of the item duet feature")
    item_stitch_status: str | None = Field(default=None, description="Status of the item stitch feature")
    landing_page_url: str | None = Field(default=None, description="URL of the landing page for the ad")
    landing_page_urls: str | None = Field(default=None, description="List of landing page URLs associated with the ad structure")
    modify_time: dt.datetime | None = Field(default=None, description="Last modification timestamp for the ad")
    music_id: str | None = Field(default=None, description="Unique identifier for the music or audio track used")
    operation_status: str | None = Field(default=None, description="Operational status of the ad")
    optimization_event: str | None = Field(default=None, description="Type of optimization event for the ad")
    page_id: str | None = Field(default=None, description="Unique identifier for the linked instant or landing page")
    playable_url: str | None = Field(default=None, description="URL of the playable ad content")
    profile_image_url: str | None = Field(default=None, description="URL of the profile image used in the ad")
    promotional_music_disabled: str | None = Field(default=None, description="Indicates if promotional music is disabled for the ad")
    secondary_status: str | None = Field(default=None, description="Secondary status of the ad")
    tiktok_item_id: str | None = Field(default=None, description="Unique TikTok item identifier for the ad")
    tracking_pixel_id: str | None = Field(default=None, description="Identifier for the tracking pixel")
    vast_moat_enabled: bool | None = Field(default=None, description="Indicates if VAST MOAT tracking is enabled")
    video_id: str | None = Field(default=None, description="Identifier for the video used in the ad")
    viewability_postbid_partner: str | None = Field(default=None, description="Viewability post-bid partner for the ad")
    viewability_vast_url: str | None = Field(default=None, description="URL for VAST viewability tracking")
