from interloper.schema import Schema
from pydantic import Field


class AdsMetadata(Schema):
    """Metadata for TikTok ads including creative, tracking, and status details."""

    ad_id: str = Field(description="Unique identifier for the ad")
    ad_name: str = Field(description="Name of the ad")
    ad_text: str = Field(description="Text content used in the ad")
    ad_format: str = Field(description="Format of the ad")
    advertiser_id: str = Field(description="Unique identifier for the advertiser")
    campaign_id: str = Field(description="Unique identifier for the campaign")
    campaign_name: str = Field(description="Name of the campaign")
    adgroup_id: str = Field(description="Unique identifier for the ad group")
    adgroup_name: str = Field(description="Name of the ad group")
    call_to_action: str = Field(description="Call to action displayed on the ad")
    call_to_action_id: str = Field(description="Identifier for the call to action")
    create_time: str = Field(description="Timestamp when the ad was created")
    modify_time: str = Field(description="Last modification timestamp")
    operation_status: str = Field(description="Operational status of the ad")
    secondary_status: str = Field(description="Secondary status of the ad")
    optimization_event: str = Field(description="Type of optimization event")
    creative_authorized: bool = Field(description="Whether the ad creative is authorized")
    identity_id: str = Field(description="Unique identifier for the ad's identity")
    identity_type: str = Field(description="Type of identity associated with the ad")
    display_name: str = Field(description="Display name associated with the ad")
    landing_page_url: str = Field(description="URL of the landing page")
    click_tracking_url: str = Field(description="URL for click tracking")
    impression_tracking_url: str = Field(description="URL for impression tracking")
    video_id: str = Field(description="Identifier for the video used in the ad")
    image_ids: str = Field(description="Comma-separated list of image IDs")
    profile_image_url: str = Field(description="URL of the profile image")
    avatar_icon_web_uri: str = Field(description="URI for the web avatar icon")
    app_name: str = Field(description="Name of the app being promoted")
    deeplink: str = Field(description="Deeplink URL for the ad")
    deeplink_type: str = Field(description="Type of deeplink used")
    playable_url: str = Field(description="URL of the playable ad content")
    tracking_pixel_id: str = Field(description="Identifier for the tracking pixel")
    tiktok_item_id: str = Field(description="Unique TikTok item identifier")
    is_new_structure: bool = Field(description="Whether the ad uses a new structure")
    is_aco: bool = Field(description="Whether the ad uses Automated Creative Optimization")
    vast_moat_enabled: bool = Field(description="Whether VAST MOAT tracking is enabled")
    viewability_postbid_partner: str = Field(description="Viewability post-bid partner")
    viewability_vast_url: str = Field(description="URL for VAST viewability tracking")
    brand_safety_postbid_partner: str = Field(description="Brand safety post-bid partner")
    aigc_disclosure_type: str = Field(description="Type of AIGC disclosure")
    dark_post_status: str = Field(description="Dark post status")
    branded_content_disabled: str = Field(description="Whether branded content is disabled")
    promotional_music_disabled: str = Field(description="Whether promotional music is disabled")
    item_stitch_status: str = Field(description="Status of the item stitch feature")
    item_duet_status: str = Field(description="Status of the item duet feature")
    fallback_type: str = Field(description="Type of fallback content used")
    identity_authorized_bc_id: str = Field(description="Authorized business center ID")
