# ###############
# PROJECT / UV
# ###############
[project]
name = "interloper-assets"
version = "0.1.0"
description = "Interloper Assets"
readme = "README.md"
authors = [{ name = "Guillaume Onfroy", email = "guillaume@digitlcloud.com" }]
requires-python = ">=3.10"
dependencies = [
    "interloper",
    "interloper-pandas",
    "httpx>=0.28.1",
    "tenacity>=9.1.2",
]

[project.optional-dependencies]
bing = ["bingads>=13.0.24.1"]
google = ["google-api-python-client>=2.167.0"]

[dependency-groups]
dev = ["pyright>=1.1.394", "ruff>=0.9.6"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
interloper = { workspace = true }
interloper-pandas = { workspace = true }

# ###############
# RUFF
# ###############
[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["E", "I", "UP", "ANN001", "ANN201", "ANN202"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"tests/**" = ["ANN"]

# ###############
# PYRIGHT
# ###############
[tool.pyright]
include = ["src"]
typeCheckingMode = "basic"
reportMissingParameterType = true
ignore = ["libs/**", "tests/**", "scripts/**"]
